In [ ]:
import requests
from dotenv import load_dotenv
import os
import json
import pandas as pd

load_dotenv()

True

In [60]:
volumes = pd.read_csv("volumes.csv")
volumes.head()

,api_detail_url,count_of_issues,date_added,date_last_updated,description,id,name,site_detail_url,start_year,first_issue_api_detail_url,...,first_issue_name,first_issue_issue_number,image_medium_url,last_issue_api_detail_url,last_issue_id,last_issue_name,last_issue_issue_number,publisher_api_detail_url,publisher_id,publisher_name
0,https://comicvine.gamespot.com/api/volume/4050...,20,2024-10-07 06:21:22,2025-10-25 20:28:42,"<p>Collected in <a href=""/absolute-batman/4050...",160294,Absolute Batman,https://comicvine.gamespot.com/absolute-batman...,2024,https://comicvine.gamespot.com/api/issue/4000-...,...,"The Zoo, Part One",1,https://comicvine.gamespot.com/a/uploads/scale...,https://comicvine.gamespot.com/api/issue/4000-...,1166236,The Straw Man,20,https://comicvine.gamespot.com/api/publisher/4...,10,DC Comics
1,https://comicvine.gamespot.com/api/volume/4050...,20,2024-10-21 07:02:31,2024-10-21 07:02:49,NaN,160511,Absolute Wonder Woman,https://comicvine.gamespot.com/absolute-wonder...,2024,https://comicvine.gamespot.com/api/issue/4000-...,...,"The Last Amazon, Part 1 of 5",1,https://comicvine.gamespot.com/a/uploads/scale...,https://comicvine.gamespot.com/api/issue/4000-...,1168224,"Season of the Witch, Part 5 of 5",20,https://comicvine.gamespot.com/api/publisher/4...,10,DC Comics
2,https://comicvine.gamespot.com/api/volume/4050...,19,2024-11-04 11:16:32,2026-01-30 09:59:34,<p>Ongoing series.</p>,160860,Absolute Superman,https://comicvine.gamespot.com/absolute-superm...,2025,https://comicvine.gamespot.com/api/issue/4000-...,...,Last Dust of Krypton - Part One: Down in the Dirt,1,https://comicvine.gamespot.com/a/uploads/scale...,https://comicvine.gamespot.com/api/issue/4000-...,1165103,"Reign of the Superman, Part Two: Red Steel in ...",19,https://comicvine.gamespot.com/api/publisher/4...,10,DC Comics
3,https://comicvine.gamespot.com/api/volume/4050...,1,2024-11-11 10:24:38,2024-11-11 10:24:53,NaN,161010,Absolute Batman Noir Edition,https://comicvine.gamespot.com/absolute-batman...,2025,https://comicvine.gamespot.com/api/issue/4000-...,...,NaN,1,https://comicvine.gamespot.com/a/uploads/scale...,https://comicvine.gamespot.com/api/issue/4000-...,1077466,NaN,1,https://comicvine.gamespot.com/api/publisher/4...,10,DC Comics
4,https://comicvine.gamespot.com/api/volume/4050...,1,2024-11-25 09:54:10,2024-11-25 09:54:30,NaN,161308,Absolute Wonder Woman Noir Edition,https://comicvine.gamespot.com/absolute-wonder...,2025,https://comicvine.gamespot.com/api/issue/4000-...,...,NaN,1,https://comicvine.gamespot.com/a/uploads/scale...,https://comicvine.gamespot.com/api/issue/4000-...,1079211,NaN,1,https://comicvine.gamespot.com/api/publisher/4...,10,DC Comics

In [61]:
batman_volume=volumes['api_detail_url'][0]
batman_volume

'https://comicvine.gamespot.com/api/volume/4050-160294/'

In [62]:
API_KEY = os.getenv("API_KEY")
BASE_URL = "https://comicvine.gamespot.com/api/"
endpoint = "volumes/"
url = batman_volume

headers = {
    "User-Agent": "absolutePipeline"  
}

params = {
        "api_key": API_KEY,
        "format": "json", 
        "field_list": "issues"
}

response = requests.get(url=url, params=params, headers=headers)

response.json()

{'error': 'OK',
 'limit': 1,
 'offset': 0,
 'number_of_page_results': 1,
 'number_of_total_results': 1,
 'status_code': 1,
 'results': {'issues': [{'api_detail_url': 'https://comicvine.gamespot.com/api/issue/4000-1073108/',
    'id': 1073108,
    'name': 'The Zoo, Part One',
    'site_detail_url': 'https://comicvine.gamespot.com/absolute-batman-1-the-zoo-part-one/4000-1073108/',
    'issue_number': '1'},
   {'api_detail_url': 'https://comicvine.gamespot.com/api/issue/4000-1077465/',
    'id': 1077465,
    'name': 'The Zoo, Part Two',
    'site_detail_url': 'https://comicvine.gamespot.com/absolute-batman-2-the-zoo-part-two/4000-1077465/',
    'issue_number': '2'},
   {'api_detail_url': 'https://comicvine.gamespot.com/api/issue/4000-1083601/',
    'id': 1083601,
    'name': 'The Zoo, Part Three',
    'site_detail_url': 'https://comicvine.gamespot.com/absolute-batman-3-the-zoo-part-three/4000-1083601/',
    'issue_number': '3'},
   {'api_detail_url': 'https://comicvine.gamespot.com/api/issue/4000-1089295/',
    'id': 1089295,
    'name': 'The Zoo, Part Four',
    'site_detail_url': 'https://comicvine.gamespot.com/absolute-batman-4-the-zoo-part-four/4000-1089295/',
    'issue_number': '4'},
   {'api_detail_url': 'https://comicvine.gamespot.com/api/issue/4000-1095530/',
    'id': 1095530,
    'name': 'The Zoo, Part Five',
    'site_detail_url': 'https://comicvine.gamespot.com/absolute-batman-5-the-zoo-part-five/4000-1095530/',
    'issue_number': '5'},
   {'api_detail_url': 'https://comicvine.gamespot.com/api/issue/4000-1099460/',
    'id': 1099460,
    'name': 'The Zoo, Part Six',
    'site_detail_url': 'https://comicvine.gamespot.com/absolute-batman-6-the-zoo-part-six/4000-1099460/',
    'issue_number': '6'},
   {'api_detail_url': 'https://comicvine.gamespot.com/api/issue/4000-1102449/',
    'id': 1102449,
    'name': 'Absolute Zero',
    'site_detail_url': 'https://comicvine.gamespot.com/absolute-batman-7-absolute-zero/4000-1102449/',
    'issue_number': '7'},
   {'api_detail_url': 'https://comicvine.gamespot.com/api/issue/4000-1109522/',
    'id': 1109522,
    'name': 'Absolute Zero',
    'site_detail_url': 'https://comicvine.gamespot.com/absolute-batman-8-absolute-zero/4000-1109522/',
    'issue_number': '8'},
   {'api_detail_url': 'https://comicvine.gamespot.com/api/issue/4000-1115570/',
    'id': 1115570,
    'name': 'Abomination, Part One',
    'site_detail_url': 'https://comicvine.gamespot.com/absolute-batman-9-abomination-part-one/4000-1115570/',
    'issue_number': '9'},
   {'api_detail_url': 'https://comicvine.gamespot.com/api/issue/4000-1120416/',
    'id': 1120416,
    'name': 'Abomination, Part Two',
    'site_detail_url': 'https://comicvine.gamespot.com/absolute-batman-10-abomination-part-two/4000-1120416/',
    'issue_number': '10'},
   {'api_detail_url': 'https://comicvine.gamespot.com/api/issue/4000-1126983/',
    'id': 1126983,
    'name': 'Abomination, Part Three',
    'site_detail_url': 'https://comicvine.gamespot.com/absolute-batman-11-abomination-part-three/4000-1126983/',
    'issue_number': '11'},
   {'api_detail_url': 'https://comicvine.gamespot.com/api/issue/4000-1131749/',
    'id': 1131749,
    'name': 'Abomination, Part Four',
    'site_detail_url': 'https://comicvine.gamespot.com/absolute-batman-12-abomination-part-four/4000-1131749/',
    'issue_number': '12'},
   {'api_detail_url': 'https://comicvine.gamespot.com/api/issue/4000-1137116/',
    'id': 1137116,
    'name': 'Abomination, Part Five',
    'site_detail_url': 'https://comicvine.gamespot.com/absolute-batman-13-abomination-part-five/4000-1137116/',
    'issue_number': '13'},
   {'api_detail_url': 'https://comicvine.gamespot.com/api/issue/4000-1145497/',
    'id': 1145497,
    'name': 'Abomination, Conclusion',
    'site_detail_url': 'https://comicvine.gamespot.com/absolute-batman-14-abomination-conclusion/4000-1145497/',
    'issue_number': '14'},
   {'api_detail_url': 'https://comicvine.gamespot.com/api/issue/4000-1147554/',
    'id': 1147554,
    'name': 'The Joker',
    'site_detail_url': 'https://comicvine.gamespot.com/absolute-batman-15-the-joker/4000-1147554/',
    'issue_number': '15'},
   {'api_detail_url': 'https://comicvine.gamespot.com/api/issue/4000-1154054/',
    'id': 1154054,
    'name': 'Bat Out of Hell',
    'site_detail_url': 'https://comicvine.gamespot.com/absolute-batman-16-bat-out-of-hell/4000-1154054/',
    'issue_number': '16'},
   {'api_detail_url': 'https://comicvine.gamespot.com/api/issue/4000-1156258/',
    'id': 1156258,
    'name': 'The Seventh Kingdom - Part 1',
    'site_detail_url': 'https://comicvine.gamespot.com/absolute-batman-17-the-seventh-kingdom-part-1/4000-1156258/',
    'issue_number': '17'},
   {'api_detail_url': 'https://comicvine.gamespot.com/api/issue/4000-1158997/',
    'id': 1158997,
    'name': 'The Seventh Kingdom - Part 2',
    'site_detail_url': 'https://comicvine.gamespot.com/absolute-batman-18-the-seventh-kingdom-part-2/4000-1158997/',
    'issue_number': '18'},
   {'api_detail_url': 'https://comicvine.gamespot.com/api/issue/4000-1163009/',
    'id': 1163009,
    'name': 'The Straw Man',
    'site_detail_url': 'https://comicvine.gamespot.com/absolute-batman-19-the-straw-man/4000-1163009/',
    'issue_number': '19'},
   {'api_detail_url': 'https://comicvine.gamespot.com/api/issue/4000-1166236/',
    'id': 1166236,
    'name': 'The Straw Man',
    'site_detail_url': 'https://comicvine.gamespot.com/absolute-batman-20-the-straw-man/4000-1166236/',
    'issue_number': '20'}]},
 'version': '1.0'}

In [49]:
data = response.json()

with open("output.json", "w") as f:
    json.dump(data, f, indent=2)

In [50]:
issues = data["results"]["issues"]
df = pd.DataFrame(issues)
df

,api_detail_url,id,name,site_detail_url,issue_number
0,https://comicvine.gamespot.com/api/issue/4000-...,1073108,"The Zoo, Part One",https://comicvine.gamespot.com/absolute-batman...,1
1,https://comicvine.gamespot.com/api/issue/4000-...,1077465,"The Zoo, Part Two",https://comicvine.gamespot.com/absolute-batman...,2
2,https://comicvine.gamespot.com/api/issue/4000-...,1083601,"The Zoo, Part Three",https://comicvine.gamespot.com/absolute-batman...,3
3,https://comicvine.gamespot.com/api/issue/4000-...,1089295,"The Zoo, Part Four",https://comicvine.gamespot.com/absolute-batman...,4
4,https://comicvine.gamespot.com/api/issue/4000-...,1095530,"The Zoo, Part Five",https://comicvine.gamespot.com/absolute-batman...,5
5,https://comicvine.gamespot.com/api/issue/4000-...,1099460,"The Zoo, Part Six",https://comicvine.gamespot.com/absolute-batman...,6
6,https://comicvine.gamespot.com/api/issue/4000-...,1102449,Absolute Zero,https://comicvine.gamespot.com/absolute-batman...,7
7,https://comicvine.gamespot.com/api/issue/4000-...,1109522,Absolute Zero,https://comicvine.gamespot.com/absolute-batman...,8
8,https://comicvine.gamespot.com/api/issue/4000-...,1115570,"Abomination, Part One",https://comicvine.gamespot.com/absolute-batman...,9
9,https://comicvine.gamespot.com/api/issue/4000-...,1120416,"Abomination, Part Two",https://comicvine.gamespot.com/absolute-batman...,10
10,https://comicvine.gamespot.com/api/issue/4000-...,1126983,"Abomination, Part Three",https://comicvine.gamespot.com/absolute-batman...,11
11,https://comicvine.gamespot.com/api/issue/4000-...,1131749,"Abomination, Part Four",https://comicvine.gamespot.com/absolute-batman...,12
12,https://comicvine.gamespot.com/api/issue/4000-...,1137116,"Abomination, Part Five",https://comicvine.gamespot.com/absolute-batman...,13
13,https://comicvine.gamespot.com/api/issue/4000-...,1145497,"Abomination, Conclusion",https://comicvine.gamespot.com/absolute-batman...,14
14,https://comicvine.gamespot.com/api/issue/4000-...,1147554,The Joker,https://comicvine.gamespot.com/absolute-batman...,15
15,https://comicvine.gamespot.com/api/issue/4000-...,1154054,Bat Out of Hell,https://comicvine.gamespot.com/absolute-batman...,16
16,https://comicvine.gamespot.com/api/issue/4000-...,1156258,The Seventh Kingdom - Part 1,https://comicvine.gamespot.com/absolute-batman...,17
17,https://comicvine.gamespot.com/api/issue/4000-...,1158997,The Seventh Kingdom - Part 2,https://comicvine.gamespot.com/absolute-batman...,18
18,https://comicvine.gamespot.com/api/issue/4000-...,1163009,The Straw Man,https://comicvine.gamespot.com/absolute-batman...,19
19,https://comicvine.gamespot.com/api/issue/4000-...,1166236,The Straw Man,https://comicvine.gamespot.com/absolute-batman...,20

In [52]:

url = df['api_detail_url'][18]

headers = {
    "User-Agent": "absolutePipeline"  
}

params = {
        "api_key": API_KEY,
        "format": "json", 
        "field_list": ["date_last_updated,character_credits,description,id,image,object_credits,person_credits,store_date,volume"]
}

response = requests.get(url=url, params=params, headers=headers)

response.json()

{'error': 'OK',
 'limit': 1,
 'offset': 0,
 'number_of_page_results': 1,
 'number_of_total_results': 1,
 'status_code': 1,
 'results': {'character_credits': [{'api_detail_url': 'https://comicvine.gamespot.com/api/character/4005-5556/',
    'id': 5556,
    'name': 'Alfred Pennyworth',
    'site_detail_url': 'https://comicvine.gamespot.com/alfred-pennyworth/4005-5556/'},
   {'api_detail_url': 'https://comicvine.gamespot.com/api/character/4005-5368/',
    'id': 5368,
    'name': 'Barbara Gordon',
    'site_detail_url': 'https://comicvine.gamespot.com/barbara-gordon/4005-5368/'},
   {'api_detail_url': 'https://comicvine.gamespot.com/api/character/4005-1699/',
    'id': 1699,
    'name': 'Batman',
    'site_detail_url': 'https://comicvine.gamespot.com/batman/4005-1699/'},
   {'api_detail_url': 'https://comicvine.gamespot.com/api/character/4005-42288/',
    'id': 42288,
    'name': 'Carmine Falcone',
    'site_detail_url': 'https://comicvine.gamespot.com/carmine-falcone/4005-42288/'},
   {'api_detail_url': 'https://comicvine.gamespot.com/api/character/4005-3588/',
    'id': 3588,
    'name': 'Deathstroke',
    'site_detail_url': 'https://comicvine.gamespot.com/deathstroke/4005-3588/'},
   {'api_detail_url': 'https://comicvine.gamespot.com/api/character/4005-1691/',
    'id': 1691,
    'name': 'Dick Grayson',
    'site_detail_url': 'https://comicvine.gamespot.com/dick-grayson/4005-1691/'},
   {'api_detail_url': 'https://comicvine.gamespot.com/api/character/4005-100777/',
    'id': 100777,
    'name': 'Duke Thomas',
    'site_detail_url': 'https://comicvine.gamespot.com/duke-thomas/4005-100777/'},
   {'api_detail_url': 'https://comicvine.gamespot.com/api/character/4005-1696/',
    'id': 1696,
    'name': 'Harley Quinn',
    'site_detail_url': 'https://comicvine.gamespot.com/harley-quinn/4005-1696/'},
   {'api_detail_url': 'https://comicvine.gamespot.com/api/character/4005-3727/',
    'id': 3727,
    'name': 'James Gordon',
    'site_detail_url': 'https://comicvine.gamespot.com/james-gordon/4005-3727/'},
   {'api_detail_url': 'https://comicvine.gamespot.com/api/character/4005-6849/',
    'id': 6849,
    'name': 'Jason Todd',
    'site_detail_url': 'https://comicvine.gamespot.com/jason-todd/4005-6849/'},
   {'api_detail_url': 'https://comicvine.gamespot.com/api/character/4005-1702/',
    'id': 1702,
    'name': 'Joker',
    'site_detail_url': 'https://comicvine.gamespot.com/joker/4005-1702/'},
   {'api_detail_url': 'https://comicvine.gamespot.com/api/character/4005-3725/',
    'id': 3725,
    'name': 'Killer Croc',
    'site_detail_url': 'https://comicvine.gamespot.com/killer-croc/4005-3725/'},
   {'api_detail_url': 'https://comicvine.gamespot.com/api/character/4005-4885/',
    'id': 4885,
    'name': 'Penguin',
    'site_detail_url': 'https://comicvine.gamespot.com/penguin/4005-4885/'},
   {'api_detail_url': 'https://comicvine.gamespot.com/api/character/4005-3726/',
    'id': 3726,
    'name': 'Scarecrow',
    'site_detail_url': 'https://comicvine.gamespot.com/scarecrow/4005-3726/'},
   {'api_detail_url': 'https://comicvine.gamespot.com/api/character/4005-6156/',
    'id': 6156,
    'name': 'Stephanie Brown',
    'site_detail_url': 'https://comicvine.gamespot.com/stephanie-brown/4005-6156/'},
   {'api_detail_url': 'https://comicvine.gamespot.com/api/character/4005-9290/',
    'id': 9290,
    'name': 'Tim Drake',
    'site_detail_url': 'https://comicvine.gamespot.com/tim-drake/4005-9290/'},
   {'api_detail_url': 'https://comicvine.gamespot.com/api/character/4005-5555/',
    'id': 5555,
    'name': 'Two-Face',
    'site_detail_url': 'https://comicvine.gamespot.com/two-face/4005-5555/'}],
  'date_last_updated': '2026-04-18 18:00:54',
  'description': "<p><em>ABSOLUTE SCARECROW EMERGES FROM THE SHADOWS OF ARK M AS A NEW STORY ARC BEGINS...</em></p><p><em>Poison Ivy proved to be just one of the many horrors within the bowels of the ARK M facility, and as Joker sets his sights on Absolute Batman, he decides to enlist the help of one of the center's most terrifying doctors, Dr. Jonathan Crane.</em></p><p><em>While Bruce Wayne tries to align himself with Barbara Gordon, there's more than one alliance formed in this issue.</em></p><p><em>New debuts, new villains, new arc starts here.</em></p>",
  'id': 1163009,
  'image': {'icon_url': 'https://comicvine.gamespot.com/a/uploads/square_avatar/11161/111615891/10041672-cover.jpg',
   'medium_url': 'https://comicvine.gamespot.com/a/uploads/scale_medium/11161/111615891/10041672-cover.jpg',
   'screen_url': 'https://comicvine.gamespot.com/a/uploads/screen_medium/11161/111615891/10041672-cover.jpg',
   'screen_large_url': 'https://comicvine.gamespot.com/a/uploads/screen_kubrick/11161/111615891/10041672-cover.jpg',
   'small_url': 'https://comicvine.gamespot.com/a/uploads/scale_small/11161/111615891/10041672-cover.jpg',
   'super_url': 'https://comicvine.gamespot.com/a/uploads/scale_large/11161/111615891/10041672-cover.jpg',
   'thumb_url': 'https://comicvine.gamespot.com/a/uploads/scale_avatar/11161/111615891/10041672-cover.jpg',
   'tiny_url': 'https://comicvine.gamespot.com/a/uploads/square_mini/11161/111615891/10041672-cover.jpg',
   'original_url': 'https://comicvine.gamespot.com/a/uploads/original/11161/111615891/10041672-cover.jpg',
   'image_tags': 'All Images'},
  'object_credits': [{'api_detail_url': 'https://comicvine.gamespot.com/api/object/4055-41463/',
    'id': 41463,
    'name': 'Batmobile',
    'site_detail_url': 'https://comicvine.gamespot.com/batmobile/4055-41463/'}],
  'person_credits': [{'api_detail_url': 'https://comicvine.gamespot.com/api/person/4040-5033/',
    'id': 5033,
    'name': 'Ariel Olivetti',
    'site_detail_url': 'https://comicvine.gamespot.com/ariel-olivetti/4040-5033/',
    'role': 'cover'},
   {'api_detail_url': 'https://comicvine.gamespot.com/api/person/4040-42775/',
    'id': 42775,
    'name': 'Ben Oliver',
    'site_detail_url': 'https://comicvine.gamespot.com/ben-oliver/4040-42775/',
    'role': 'cover'},
   {'api_detail_url': 'https://comicvine.gamespot.com/api/person/4040-56273/',
    'id': 56273,
    'name': 'Chris Conroy',
    'site_detail_url': 'https://comicvine.gamespot.com/chris-conroy/4040-56273/',
    'role': 'editor'},
   {'api_detail_url': 'https://comicvine.gamespot.com/api/person/4040-52357/',
    'id': 52357,
    'name': 'Frank Martin Jr.',
    'site_detail_url': 'https://comicvine.gamespot.com/frank-martin-jr/4040-52357/',
    'role': 'colorist, cover'},
   {'api_detail_url': 'https://comicvine.gamespot.com/api/person/4040-61095/',
    'id': 61095,
    'name': 'Katie Kubert',
    'site_detail_url': 'https://comicvine.gamespot.com/katie-kubert/4040-61095/',
    'role': 'editor'},
   {'api_detail_url': 'https://comicvine.gamespot.com/api/person/4040-2629/',
    'id': 2629,
    'name': 'Liam Sharp',
    'site_detail_url': 'https://comicvine.gamespot.com/liam-sharp/4040-2629/',
    'role': 'cover'},
   {'api_detail_url': 'https://comicvine.gamespot.com/api/person/4040-25538/',
    'id': 25538,
    'name': 'Marie Javins',
    'site_detail_url': 'https://comicvine.gamespot.com/marie-javins/4040-25538/',
    'role': 'other'},
   {'api_detail_url': 'https://comicvine.gamespot.com/api/person/4040-41789/',
    'id': 41789,
    'name': 'Nick Dragotta',
    'site_detail_url': 'https://comicvine.gamespot.com/nick-dragotta/4040-41789/',
    'role': 'artist, cover'},
   {'api_detail_url': 'https://comicvine.gamespot.com/api/person/4040-132895/',
    'id': 132895,
    'name': 'Sabrina Futch',
    'site_detail_url': 'https://comicvine.gamespot.com/sabrina-futch/4040-132895/',
    'role': 'editor'},
   {'api_detail_url': 'https://comicvine.gamespot.com/api/person/4040-58926/',
    'id': 58926,
    'name': 'Scott Snyder',
    'site_detail_url': 'https://comicvine.gamespot.com/scott-snyder/4040-58926/',
    'role': 'writer'},
   {'api_detail_url': 'https://comicvine.gamespot.com/api/person/4040-83732/',
    'id': 83732,
    'name': 'Tom Napolitano',
    'site_detail_url': 'https://comicvine.gamespot.com/tom-napolitano/4040-83732/',
    'role': 'letterer'}],
  'store_date': '2026-04-15',
  'volume': {'api_detail_url': 'https://comicvine.gamespot.com/api/volume/4050-160294/',
   'id': 160294,
   'name': 'Absolute Batman',
   'site_detail_url': 'https://comicvine.gamespot.com/absolute-batman/4050-160294/'}},
 'version': '1.0'}

In [53]:
data = response.json()

with open("issue_details.json", "w") as f:
    json.dump(data, f, indent=2)

In [ ]:
#Get characters in issue
characters_json = data["results"]["character_credits"]
characters_list = []
for character in characters_json: 
    characters_list.append(character.get("name"))
    #print(character)
# get description
description= data["results"]["description"]
# get image
image_url = data["results"]["image"]["medium_url"]
# get objects
objects_json = data["results"]["object_credits"]
objects_list = []
for object in objects_json: 
    objects_list.append(object.get("name"))
# get credits
persons_json = data["results"]["person_credits"] 
for person in persons_json: 
    colorists = [p["name"] for p in persons_json if "colorist" in p.get("role", "")]
    artists = [p["name"] for p in persons_json if "artist" in p.get("role", "")]
    writers = [p["name"] for p in persons_json if "writer" in p.get("role", "")]
#  get store date
store_date = data["results"]["store_date"] 
# volume id
volume_id = data["results"]["volume"]["id"]

['Alfred Pennyworth',
 'Barbara Gordon',
 'Batman',
 'Carmine Falcone',
 'Deathstroke',
 'Dick Grayson',
 'Duke Thomas',
 'Harley Quinn',
 'James Gordon',
 'Jason Todd',
 'Joker',
 'Killer Croc',
 'Penguin',
 'Scarecrow',
 'Stephanie Brown',
 'Tim Drake',
 'Two-Face']

In [41]:
df.at[18, "characters"] = characters_list
df.at[18, "description"] = description
df.at[18, "image_url"] = image_url
df.at[18, "objects"] = objects_list
df.at[18, "colorists"] = colorists
df.at[18, "artists"] = artists
df.at[18, "writers"] = writers
df.at[18, "store_date"] = store_date
df.at[18, "volume_id"] = int(volume_id)
df

,api_detail_url,id,name,site_detail_url,issue_number,characters,description,image_url,objects,colorists,artists,writers,store_date,volume_id
0,https://comicvine.gamespot.com/api/issue/4000-...,1073108,"The Zoo, Part One",https://comicvine.gamespot.com/absolute-batman...,1,nan,NaN,NaN,nan,nan,nan,nan,NaN,NaN
1,https://comicvine.gamespot.com/api/issue/4000-...,1077465,"The Zoo, Part Two",https://comicvine.gamespot.com/absolute-batman...,2,nan,NaN,NaN,nan,nan,nan,nan,NaN,NaN
2,https://comicvine.gamespot.com/api/issue/4000-...,1083601,"The Zoo, Part Three",https://comicvine.gamespot.com/absolute-batman...,3,nan,NaN,NaN,nan,nan,nan,nan,NaN,NaN
3,https://comicvine.gamespot.com/api/issue/4000-...,1089295,"The Zoo, Part Four",https://comicvine.gamespot.com/absolute-batman...,4,nan,NaN,NaN,nan,nan,nan,nan,NaN,NaN
4,https://comicvine.gamespot.com/api/issue/4000-...,1095530,"The Zoo, Part Five",https://comicvine.gamespot.com/absolute-batman...,5,nan,NaN,NaN,nan,nan,nan,nan,NaN,NaN
5,https://comicvine.gamespot.com/api/issue/4000-...,1099460,"The Zoo, Part Six",https://comicvine.gamespot.com/absolute-batman...,6,nan,NaN,NaN,nan,nan,nan,nan,NaN,NaN
6,https://comicvine.gamespot.com/api/issue/4000-...,1102449,Absolute Zero,https://comicvine.gamespot.com/absolute-batman...,7,nan,NaN,NaN,nan,nan,nan,nan,NaN,NaN
7,https://comicvine.gamespot.com/api/issue/4000-...,1109522,Absolute Zero,https://comicvine.gamespot.com/absolute-batman...,8,nan,NaN,NaN,nan,nan,nan,nan,NaN,NaN
8,https://comicvine.gamespot.com/api/issue/4000-...,1115570,"Abomination, Part One",https://comicvine.gamespot.com/absolute-batman...,9,nan,NaN,NaN,nan,nan,nan,nan,NaN,NaN
9,https://comicvine.gamespot.com/api/issue/4000-...,1120416,"Abomination, Part Two",https://comicvine.gamespot.com/absolute-batman...,10,nan,NaN,NaN,nan,nan,nan,nan,NaN,NaN
10,https://comicvine.gamespot.com/api/issue/4000-...,1126983,"Abomination, Part Three",https://comicvine.gamespot.com/absolute-batman...,11,nan,NaN,NaN,nan,nan,nan,nan,NaN,NaN
11,https://comicvine.gamespot.com/api/issue/4000-...,1131749,"Abomination, Part Four",https://comicvine.gamespot.com/absolute-batman...,12,nan,NaN,NaN,nan,nan,nan,nan,NaN,NaN
12,https://comicvine.gamespot.com/api/issue/4000-...,1137116,"Abomination, Part Five",https://comicvine.gamespot.com/absolute-batman...,13,nan,NaN,NaN,nan,nan,nan,nan,NaN,NaN
13,https://comicvine.gamespot.com/api/issue/4000-...,1145497,"Abomination, Conclusion",https://comicvine.gamespot.com/absolute-batman...,14,nan,NaN,NaN,nan,nan,nan,nan,NaN,NaN
14,https://comicvine.gamespot.com/api/issue/4000-...,1147554,The Joker,https://comicvine.gamespot.com/absolute-batman...,15,nan,NaN,NaN,nan,nan,nan,nan,NaN,NaN
15,https://comicvine.gamespot.com/api/issue/4000-...,1154054,Bat Out of Hell,https://comicvine.gamespot.com/absolute-batman...,16,nan,NaN,NaN,nan,nan,nan,nan,NaN,NaN
16,https://comicvine.gamespot.com/api/issue/4000-...,1156258,The Seventh Kingdom - Part 1,https://comicvine.gamespot.com/absolute-batman...,17,nan,NaN,NaN,nan,nan,nan,nan,NaN,NaN
17,https://comicvine.gamespot.com/api/issue/4000-...,1158997,The Seventh Kingdom - Part 2,https://comicvine.gamespot.com/absolute-batman...,18,nan,NaN,NaN,nan,nan,nan,nan,NaN,NaN
18,https://comicvine.gamespot.com/api/issue/4000-...,1163009,The Straw Man,https://comicvine.gamespot.com/absolute-batman...,19,"[Alfred Pennyworth, Barbara Gordon, Batman, Ca...",<p><em>ABSOLUTE SCARECROW EMERGES FROM THE SHA...,https://comicvine.gamespot.com/a/uploads/scale...,[Batmobile],[Frank Martin Jr.],[Nick Dragotta],[Scott Snyder],2026-04-15,160294.0
19,https://comicvine.gamespot.com/api/issue/4000-...,1166236,The Straw Man,https://comicvine.gamespot.com/absolute-batman...,20,nan,NaN,NaN,nan,nan,nan,nan,NaN,NaN

### Populate data of all issues

In [ ]:
batman_issues_data = response.json()
issues = batman_issues_data["results"]["issues"]
batman_issues_df = pd.DataFrame(issues)
batman_issues_df

,api_detail_url,id,name,site_detail_url,issue_number
0,https://comicvine.gamespot.com/api/issue/4000-...,1073108,"The Zoo, Part One",https://comicvine.gamespot.com/absolute-batman...,1
1,https://comicvine.gamespot.com/api/issue/4000-...,1077465,"The Zoo, Part Two",https://comicvine.gamespot.com/absolute-batman...,2
2,https://comicvine.gamespot.com/api/issue/4000-...,1083601,"The Zoo, Part Three",https://comicvine.gamespot.com/absolute-batman...,3
3,https://comicvine.gamespot.com/api/issue/4000-...,1089295,"The Zoo, Part Four",https://comicvine.gamespot.com/absolute-batman...,4
4,https://comicvine.gamespot.com/api/issue/4000-...,1095530,"The Zoo, Part Five",https://comicvine.gamespot.com/absolute-batman...,5
5,https://comicvine.gamespot.com/api/issue/4000-...,1099460,"The Zoo, Part Six",https://comicvine.gamespot.com/absolute-batman...,6
6,https://comicvine.gamespot.com/api/issue/4000-...,1102449,Absolute Zero,https://comicvine.gamespot.com/absolute-batman...,7
7,https://comicvine.gamespot.com/api/issue/4000-...,1109522,Absolute Zero,https://comicvine.gamespot.com/absolute-batman...,8
8,https://comicvine.gamespot.com/api/issue/4000-...,1115570,"Abomination, Part One",https://comicvine.gamespot.com/absolute-batman...,9
9,https://comicvine.gamespot.com/api/issue/4000-...,1120416,"Abomination, Part Two",https://comicvine.gamespot.com/absolute-batman...,10
10,https://comicvine.gamespot.com/api/issue/4000-...,1126983,"Abomination, Part Three",https://comicvine.gamespot.com/absolute-batman...,11
11,https://comicvine.gamespot.com/api/issue/4000-...,1131749,"Abomination, Part Four",https://comicvine.gamespot.com/absolute-batman...,12
12,https://comicvine.gamespot.com/api/issue/4000-...,1137116,"Abomination, Part Five",https://comicvine.gamespot.com/absolute-batman...,13
13,https://comicvine.gamespot.com/api/issue/4000-...,1145497,"Abomination, Conclusion",https://comicvine.gamespot.com/absolute-batman...,14
14,https://comicvine.gamespot.com/api/issue/4000-...,1147554,The Joker,https://comicvine.gamespot.com/absolute-batman...,15
15,https://comicvine.gamespot.com/api/issue/4000-...,1154054,Bat Out of Hell,https://comicvine.gamespot.com/absolute-batman...,16
16,https://comicvine.gamespot.com/api/issue/4000-...,1156258,The Seventh Kingdom - Part 1,https://comicvine.gamespot.com/absolute-batman...,17
17,https://comicvine.gamespot.com/api/issue/4000-...,1158997,The Seventh Kingdom - Part 2,https://comicvine.gamespot.com/absolute-batman...,18
18,https://comicvine.gamespot.com/api/issue/4000-...,1163009,The Straw Man,https://comicvine.gamespot.com/absolute-batman...,19
19,https://comicvine.gamespot.com/api/issue/4000-...,1166236,The Straw Man,https://comicvine.gamespot.com/absolute-batman...,20

In [ ]:
for row in batman_issues_df.itertuples():
    print(row.Index, row.api_detail_url)