In [28]:
import requests
from dotenv import load_dotenv
import os
import json
import pandas as pd

load_dotenv()

True

In [23]:
API_KEY = os.getenv("API_KEY")
BASE_URL = "https://comicvine.gamespot.com/api/"
endpoint = "volumes/"
url = BASE_URL + endpoint

headers = {
    "User-Agent": "absolutePipeline"  
}

params = {
        "api_key": API_KEY,
          "format": "json", 
          "filter": "name:Absolute",
}

response = requests.get(url=url, params=params, headers=headers)

response.json()

{'error': 'OK',
 'limit': 100,
 'offset': 0,
 'number_of_page_results': 100,
 'number_of_total_results': 172,
 'status_code': 1,
 'results': [{'aliases': None,
   'api_detail_url': 'https://comicvine.gamespot.com/api/volume/4050-9336/',
   'count_of_issues': 4,
   'date_added': '2008-06-06 11:08:27',
   'date_last_updated': '2016-12-06 02:32:48',
   'deck': None,
   'description': '<p>It\'s the return of everyone\'s favorite hormone-crazed comic book teenagers. Bleu Finnegan and the gang are back for another hilarious round of adolescent warfare. The battle begins when Alan and Victor engage in their deranged idea of a courtship ritual - videotaping Bleu while she\'s taking a bath! What follows is an all-out nuclear holocaust, as the girls make it their mission to retrieve the tape and restore Bleu\'s devastated reputation. Unfortunately, the damage may already be done. Bleu is convinced Mr. Bishop, the teacher who is her most pronounced crush, thinks she\'s a slut, and she begins to be haunted by a mischievous pooka spirit who\'s taken the form of a giant, talking otter. Worse still, now the boys are fighting for her affection - thanks to Erin getting involved and stirring up their emotions. With the odds stacked against her, can Bleu find a way to get the contraband video out of Alan\'s sweaty hands and still walk with her head held high?</p><h4>Collected Editions</h4><ul><li><a href="https://comicvine.gamespot.com/blue-monday-absolute-beginners/4050-28342/" data-ref-id="4050-28342">Blue Monday: Absolute Beginners</a></li><li><a href="https://comicvine.gamespot.com/blue-monday-absolute-beginners/4050-96274/" data-ref-id="4050-96274">Blue Monday: Absolute Beginners</a></li></ul>',
   'first_issue': {'api_detail_url': 'https://comicvine.gamespot.com/api/issue/4000-74771/',
    'id': 74771,
    'name': 'Something About You',
    'issue_number': '1'},
   'id': 9336,
   'image': {'icon_url': 'https://comicvine.gamespot.com/a/uploads/square_avatar/6/67663/3243305-01.jpg',
    'medium_url': 'https://comicvine.gamespot.com/a/uploads/scale_medium/6/67663/3243305-01.jpg',
    'screen_url': 'https://comicvine.gamespot.com/a/uploads/screen_medium/6/67663/3243305-01.jpg',
    'screen_large_url': 'https://comicvine.gamespot.com/a/uploads/screen_kubrick/6/67663/3243305-01.jpg',
    'small_url': 'https://comicvine.gamespot.com/a/uploads/scale_small/6/67663/3243305-01.jpg',
    'super_url': 'https://comicvine.gamespot.com/a/uploads/scale_large/6/67663/3243305-01.jpg',
    'thumb_url': 'https://comicvine.gamespot.com/a/uploads/scale_avatar/6/67663/3243305-01.jpg',
    'tiny_url': 'https://comicvine.gamespot.com/a/uploads/square_mini/6/67663/3243305-01.jpg',
    'original_url': 'https://comicvine.gamespot.com/a/uploads/original/6/67663/3243305-01.jpg',
    'image_tags': 'All Images'},
   'last_issue': {'api_detail_url': 'https://comicvine.gamespot.com/api/issue/4000-74774/',
    'id': 74774,
    'name': "Hands Off, She's Mine",
    'issue_number': '4'},
   'name': 'Blue Monday: Absolute Beginners',
   'publisher': {'api_detail_url': 'https://comicvine.gamespot.com/api/publisher/4010-682/',
    'id': 682,
    'name': 'Oni Press'},
   'site_detail_url': 'https://comicvine.gamespot.com/blue-monday-absolute-beginners/4050-9336/',
   'start_year': '2001'},
  {'aliases': None,
   'api_detail_url': 'https://comicvine.gamespot.com/api/volume/4050-18627/',
   'count_of_issues': 1,
   'date_added': '2008-06-06 11:08:35',
   'date_last_updated': '2023-05-27 00:27:56',
   'deck': None,
   'description': '<p>Gives a preview of what is coming up in DC Vertigo titles and storylines, plus some extra features like exclusive stories and artwork.</p>',
   'first_issue': {'api_detail_url': 'https://comicvine.gamespot.com/api/issue/4000-109878/',
    'id': 109878,
    'name': 'Absolute Vertigo',
    'issue_number': '1'},
   'id': 18627,
   'image': {'icon_url': 'https://comicvine.gamespot.com/a/uploads/square_avatar/0/3125/126827-18627-109878-1-absolute-vertigo.jpg',
    'medium_url': 'https://comicvine.gamespot.com/a/uploads/scale_medium/0/3125/126827-18627-109878-1-absolute-vertigo.jpg',
    'screen_url': 'https://comicvine.gamespot.com/a/uploads/screen_medium/0/3125/126827-18627-109878-1-absolute-vertigo.jpg',
    'screen_large_url': 'https://comicvine.gamespot.com/a/uploads/screen_kubrick/0/3125/126827-18627-109878-1-absolute-vertigo.jpg',
    'small_url': 'https://comicvine.gamespot.com/a/uploads/scale_small/0/3125/126827-18627-109878-1-absolute-vertigo.jpg',
    'super_url': 'https://comicvine.gamespot.com/a/uploads/scale_large/0/3125/126827-18627-109878-1-absolute-vertigo.jpg',
    'thumb_url': 'https://comicvine.gamespot.com/a/uploads/scale_avatar/0/3125/126827-18627-109878-1-absolute-vertigo.jpg',
    'tiny_url': 'https://comicvine.gamespot.com/a/uploads/square_mini/0/3125/126827-18627-109878-1-absolute-vertigo.jpg',
    'original_url': 'https://comicvine.gamespot.com/a/uploads/original/0/3125/126827-18627-109878-1-absolute-vertigo.jpg',
    'image_tags': 'All Images'},
   'last_issue': {'api_detail_url': 'https://comicvine.gamespot.com/api/issue/4000-109878/',
    'id': 109878,
    'name': 'Absolute Vertigo',
    'issue_number': '1'},
   'name': 'Absolute Vertigo',
   'publisher': {'api_detail_url': 'https://comicvine.gamespot.com/api/publisher/4010-10/',
    'id': 10,
    'name': 'DC Comics'},
   'site_detail_url': 'https://comicvine.gamespot.com/absolute-vertigo/4050-18627/',
   'start_year': '1995'},
  {'aliases': None,
   'api_detail_url': 'https://comicvine.gamespot.com/api/volume/4050-22759/',
   'count_of_issues': 6,
   'date_added': '2008-08-27 09:20:29',
   'date_last_updated': '2024-01-15 10:05:59',
   'deck': None,
   'description': '<p>Riiko Izawa has never had a boyfriend and she has been rejected by every boy she has ever had a crush on. When she returns a lost cell phone to an oddly dressed salesman, she mentions wanting a boyfriend so to thank her, he directs her to his company\'s website, Kronos Heaven. When she visits the site, Riiko finds it\'s a site to create your own lover. Thinking its a game, she customizes and accidentally orders one. The next day, her new lover arrives. Following the instruction manual, she kisses him to wake him up and configure him to be in love with only her. She names him "Night " After a few weeks she is soon caught in a love triangle between Night and her childhood friend Soshi, who declares his love for her out of fear he will lose her.</p>',
   'first_issue': {'api_detail_url': 'https://comicvine.gamespot.com/api/issue/4000-136504/',
    'id': 136504,
    'name': 'Vol. 1',
    'issue_number': '1'},
   'id': 22759,
   'image': {'icon_url': 'https://comicvine.gamespot.com/a/uploads/square_avatar/2/23749/517494-67849_20070418092401_large.jpg',
    'medium_url': 'https://comicvine.gamespot.com/a/uploads/scale_medium/2/23749/517494-67849_20070418092401_large.jpg',
    'screen_url': 'https://comicvine.gamespot.com/a/uploads/screen_medium/2/23749/517494-67849_20070418092401_large.jpg',
    'screen_large_url': 'https://comicvine.gamespot.com/a/uploads/screen_kubrick/2/23749/517494-67849_20070418092401_large.jpg',
    'small_url': 'https://comicvine.gamespot.com/a/uploads/scale_small/2/23749/517494-67849_20070418092401_large.jpg',
    'super_url': 'https://comicvine.gamespot.com/a/uploads/scale_large/2/23749/517494-67849_20070418092401_large.jpg',
    'thumb_url': 'https://comicvine.gamespot.com/a/uploads/scale_avatar/2/23749/517494-67849_20070418092401_large.jpg',
    'tiny_url': 'https://comicvine.gamespot.com/a/uploads/square_mini/2/23749/517494-67849_20070418092401_large.jpg',
    'original_url': 'https://comicvine.gamespot.com/a/uploads/original/2/23749/517494-67849_20070418092401_large.jpg',
    'image_tags': 'All Images'},
   'last_issue': {'api_detail_url': 'https://comicvine.gamespot.com/api/issue/4000-136510/',
    'id': 136510,
    'name': 'Vol. 6',
    'issue_number': '6'},
   'name': 'Absolute Boyfriend',
   'publisher': {'api_detail_url': 'https://comicvine.gamespot.com/api/publisher/4010-428/',
    'id': 428,
    'name': 'Viz'},
   'site_detail_url': 'https://comicvine.gamespot.com/absolute-boyfriend/4050-22759/',
   'start_year': '2006'},
  {'aliases': None,
   'api_detail_url': 'https://comicvine.gamespot.com/api/volume/4050-22760/',
   'count_of_issues': 1,
   'date_added': '2008-08-27 09:41:09',
   'date_last_updated': '2020-01-20 19:12:52',
   'deck': None,
   'description': '<p>Deluxe hardcover that collects Batman: The Dark Knight Returns 1-4 and Batman: The Dark Knight Strikes Again 1-3. Cover price $99.99.</p>',
   'first_issue': {'api_detail_url': 'https://comicvine.gamespot.com/api/issue/4000-136511/',
    'id': 136511,
    'name': 'Absolute Edition',
    'issue_number': '1'},
   'id': 22760,
   'image': {'icon_url': 'https://comicvine.gamespot.com/a/uploads/square_avatar/2/23749/517510-65439_20080406054219_large.jpg',
    'medium_url': 'https://comicvine.gamespot.com/a/uploads/scale_medium/2/23749/517510-65439_20080406054219_large.jpg',
    'screen_url': 'https://comicvine.gamespot.com/a/uploads/screen_medium/2/23749/517510-65439_20080406054219_large.jpg',
    'screen_large_url': 'https://comicvine.gamespot.com/a/uploads/screen_kubrick/2/23749/517510-65439_20080406054219_large.jpg',
    'small_url': 'https://comicvine.gamespot.com/a/uploads/scale_small/2/23749/517510-65439_20080406054219_large.jpg',
    'super_url': 'https://comicvine.gamespot.com/a/uploads/scale_large/2/23749/517510-65439_20080406054219_large.jpg',
    'thumb_url': 'https://comicvine.gamespot.com/a/uploads/scale_avatar/2/23749/517510-65439_20080406054219_large.jpg',
    'tiny_url': 'https://comicvine.gamespot.com/a/uploads/square_mini/2/23749/517510-65439_20080406054219_large.jpg',
    'original_url': 'https://comicvine.gamespot.com/a/uploads/original/2/23749/517510-65439_20080406054219_large.jpg',
    'image_tags': 'All Images'},
   'last_issue': {'api_detail_url': 'https://comicvine.gamespot.com/api/issue/4000-136511/',
    'id': 136511,
    'name': 'Absolute Edition',
    'issue_number': '1'},
   'name': 'Absolute Dark Knight',
   'publisher': {'api_detail_url': 'https://comicvine.gamespot.com/api/publisher/4010-10/',
    'id': 10,
    'name': 'DC Comics'},
   'site_detail_url': 'https://comicvine.gamespot.com/absolute-dark-knight/4050-22760/',
   'start_year': '2006'},
  {'aliases': None,
   'api_detail_url': 'https://comicvine.gamespot.com/api/volume/4050-22761/',
   'count_of_issues': 6,
   'date_added': '2008-08-27 09:49:50',
   'date_last_updated': '2014-01-20 04:57:24',
   'deck': None,
   'description': None,
   'first_issue': {'api_detail_url': 'https://comicvine.gamespot.com/api/issue/4000-136516/',
    'id': 136516,
    'name': None,
    'issue_number': '1'},
   'id': 22761,
   'image': {'icon_url': 'https://comicvine.gamespot.com/a/uploads/square_avatar/6/67663/3586184-01.jpg',
    'medium_url': 'https://comicvine.gamespot.com/a/uploads/scale_medium/6/67663/3586184-01.jpg',
    'screen_url': 'https://comicvine.gamespot.com/a/uploads/screen_medium/6/67663/3586184-01.jpg',
    'screen_large_url': 'https://comicvine.gamespot.com/a/uploads/screen_kubrick/6/67663/3586184-01.jpg',
    'small_url': 'https://comicvine.gamespot.com/a/uploads/scale_small/6/67663/3586184-01.jpg',
    'super_url': 'https://comicvine.gamespot.com/a/uploads/scale_large/6/67663/3586184-01.jpg',
    'thumb_url': 'https://comicvine.gamespot.com/a/uploads/scale_avatar/6/67663/3586184-01.jpg',
    'tiny_url': 'https://comicvine.gamespot.com/a/uploads/square_mini/6/67663/3586184-01.jpg',
    'original_url': 'https://comicvine.gamespot.com/a/uploads/original/6/67663/3586184-01.jpg',
    'image_tags': 'All Images'},
   'last_issue': {'api_detail_url': 'https://comicvine.gamespot.com/api/issue/4000-136514/',
    'id': 136514,
    'name': None,
    'issue_number': '6'},
   'name': 'Absolute Zero',
   'publisher': {'api_detail_url': 'https://comicvine.gamespot.com/api/publisher/4010-488/',
    'id': 488,
    'name': 'Antarctic Press'},
   'site_detail_url': 'https://comicvine.gamespot.com/absolute-zero/4050-22761/',
   'start_year': '1995'},
  {'aliases': None,
   'api_detail_url': 'https://comicvine.gamespot.com/api/volume/4050-22766/',
   'count_of_issues': 3,
   'date_added': '2008-08-27 20:45:53',
   'date_last_updated': '2009-01-08 15:14:43',
   'deck': None,
   'description': None,
   'first_issue': {'api_detail_url': 'https://comicvine.gamespot.com/api/issue/4000-136583/',
    'id': 136583,
    'name': 'Honey I Blew Up the Origin',
    'issue_number': '1'},
   'id': 22766,
   'image': {'icon_url': 'https://comicvine.gamespot.com/a/uploads/square_avatar/2/23749/518260-9293_20051117005224_large.jpg',
    'medium_url': 'https://comicvine.gamespot.com/a/uploads/scale_medium/2/23749/518260-9293_20051117005224_large.jpg',
    'screen_url': 'https://comicvine.gamespot.com/a/uploads/screen_medium/2/23749/518260-9293_20051117005224_large.jpg',
    'screen_large_url': 'https://comicvine.gamespot.com/a/uploads/screen_kubrick/2/23749/518260-9293_20051117005224_large.jpg',
    'small_url': 'https://comicvine.gamespot.com/a/uploads/scale_small/2/23749/518260-9293_20051117005224_large.jpg',
    'super_url': 'https://comicvine.gamespot.com/a/uploads/scale_large/2/23749/518260-9293_20051117005224_large.jpg',
    'thumb_url': 'https://comicvine.gamespot.com/a/uploads/scale_avatar/2/23749/518260-9293_20051117005224_large.jpg',
    'tiny_url': 'https://comicvine.gamespot.com/a/uploads/square_mini/2/23749/518260-9293_20051117005224_large.jpg',
    'original_url': 'https://comicvine.gamespot.com/a/uploads/original/2/23749/518260-9293_20051117005224_large.jpg',
    'image_tags': 'All Images'},
   'last_issue': {'api_detail_url': 'https://comicvine.gamespot.com/api/issue/4000-136586/',
    'id': 136586,
    'name': "Where there's Smoke...there's Firewire!",
    'issue_number': '3'},
   'name': 'Absolute Zeroes',
   'publisher': {'api_detail_url': 'https://comicvine.gamespot.com/api/publisher/4010-2047/',
    'id': 2047,
    'name': 'Ronin Studios'},
   'site_detail_url': 'https://comicvine.gamespot.com/absolute-zeroes/4050-22766/',
   'start_year': '2005'},
  {'aliases': None,
   'api_detail_url': 'https://comicvine.gamespot.com/api/volume/4050-25048/',
   'count_of_issues': 1,
   'date_added': '2008-12-20 22:15:15',
   'date_last_updated': '2009-01-08 15:16:01',
   'deck': None,
   'description': None,
   'first_issue': {'api_detail_url': 'https://comicvine.gamespot.com/api/issue/4000-147954/',
    'id': 147954,
    'name': 'The Absolute Edition',
    'issue_number': '1'},
   'id': 25048,
   'image': {'icon_url': 'https://comicvine.gamespot.com/a/uploads/square_avatar/2/26751/650888-absolute1.jpg',
    'medium_url': 'https://comicvine.gamespot.com/a/uploads/scale_medium/2/26751/650888-absolute1.jpg',
    'screen_url': 'https://comicvine.gamespot.com/a/uploads/screen_medium/2/26751/650888-absolute1.jpg',
    'screen_large_url': 'https://comicvine.gamespot.com/a/uploads/screen_kubrick/2/26751/650888-absolute1.jpg',
    'small_url': 'https://comicvine.gamespot.com/a/uploads/scale_small/2/26751/650888-absolute1.jpg',
    'super_url': 'https://comicvine.gamespot.com/a/uploads/scale_large/2/26751/650888-absolute1.jpg',
    'thumb_url': 'https://comicvine.gamespot.com/a/uploads/scale_avatar/2/26751/650888-absolute1.jpg',
    'tiny_url': 'https://comicvine.gamespot.com/a/uploads/square_mini/2/26751/650888-absolute1.jpg',
    'original_url': 'https://comicvine.gamespot.com/a/uploads/original/2/26751/650888-absolute1.jpg',
    'image_tags': 'All Images'},
   'last_issue': {'api_detail_url': 'https://comicvine.gamespot.com/api/issue/4000-147954/',
    'id': 147954,
    'name': 'The Absolute Edition',
    'issue_number': '1'},
   'name': 'Absolute Crisis On Infinite Earths',
   'publisher': {'api_detail_url': 'https://comicvine.gamespot.com/api/publisher/4010-10/',
    'id': 10,
    'name': 'DC Comics'},
   'site_detail_url': 'https://comicvine.gamespot.com/absolute-crisis-on-infinite-earths/4050-25048/',
   'start_year': '2005'},
  {'aliases': None,
   'api_detail_url': 'https://comicvine.gamespot.com/api/volume/4050-27636/',
   'count_of_issues': 5,
   'date_added': '2009-08-30 19:58:57',
   'date_last_updated': '2023-05-30 03:45:04',
   'deck': None,
   'description': '<p><a data-ref-id="4050-4207" href="/the-sandman/4050-4207/" slug="the-sandman">The Sandman</a> series collected in five over sized absolute edition hardcovers.</p>',
   'first_issue': {'api_detail_url': 'https://comicvine.gamespot.com/api/issue/4000-176836/',
    'id': 176836,
    'name': 'Vol. 1',
    'issue_number': '1'},
   'id': 27636,
   'image': {'icon_url': 'https://comicvine.gamespot.com/a/uploads/square_avatar/0/9116/997443-v1.jpg',
    'medium_url': 'https://comicvine.gamespot.com/a/uploads/scale_medium/0/9116/997443-v1.jpg',
    'screen_url': 'https://comicvine.gamespot.com/a/uploads/screen_medium/0/9116/997443-v1.jpg',
    'screen_large_url': 'https://comicvine.gamespot.com/a/uploads/screen_kubrick/0/9116/997443-v1.jpg',
    'small_url': 'https://comicvine.gamespot.com/a/uploads/scale_small/0/9116/997443-v1.jpg',
    'super_url': 'https://comicvine.gamespot.com/a/uploads/scale_large/0/9116/997443-v1.jpg',
    'thumb_url': 'https://comicvine.gamespot.com/a/uploads/scale_avatar/0/9116/997443-v1.jpg',
    'tiny_url': 'https://comicvine.gamespot.com/a/uploads/square_mini/0/9116/997443-v1.jpg',
    'original_url': 'https://comicvine.gamespot.com/a/uploads/original/0/9116/997443-v1.jpg',
    'image_tags': 'All Images'},
   'last_issue': {'api_detail_url': 'https://comicvine.gamespot.com/api/issue/4000-301102/',
    'id': 301102,
    'name': 'Vol. 5',
    'issue_number': '5'},
   'name': 'Absolute Sandman',
   'publisher': {'api_detail_url': 'https://comicvine.gamespot.com/api/publisher/4010-10/',
    'id': 10,
    'name': 'DC Comics'},
   'site_detail_url': 'https://comicvine.gamespot.com/absolute-sandman/4050-27636/',
   'start_year': '2006'},
  {'aliases': None,
   'api_detail_url': 'https://comicvine.gamespot.com/api/volume/4050-27761/',
   'count_of_issues': 1,
   'date_added': '2009-09-06 16:38:48',
   'date_last_updated': '2023-05-29 20:50:50',
   'deck': None,
   'description': '<figure data-align="right" data-embed-type="image" data-img-src="https://static.comicvine.com/uploads/original/6/62444/1582472-51jartegyfl.jpg" data-ref-id="1300-1582472" data-size="medium" data-ratio="0.736"><a class="fluid-height" style="padding-bottom:73.6%" href="https://static.comicvine.com/uploads/original/6/62444/1582472-51jartegyfl.jpg" data-ref-id="1300-1582472"><img alt="\xa0example of cover" src="https://comicvine.gamespot.com/a/uploads/scale_medium/6/62444/1582472-51jartegyfl.jpg" srcset="https://comicvine.gamespot.com/a/uploads/original/6/62444/1582472-51jartegyfl.jpg 500w, https://comicvine.gamespot.com/a/uploads/scale_medium/6/62444/1582472-51jartegyfl.jpg 480w" sizes="(max-width: 480px) 100vw, 480px" data-width="480"></a><figcaption>\xa0example of cover</figcaption></figure>     An oversized hardcover collection with the slipcase of V for Vendetta.\xa0 There are bonus materials and finally the covers on the mini-series are added as chapter breaks.\xa0 The covers were omitted in early trade printings.',
   'first_issue': {'api_detail_url': 'https://comicvine.gamespot.com/api/issue/4000-169882/',
    'id': 169882,
    'name': 'HC',
    'issue_number': '1'},
   'id': 27761,
   'image': {'icon_url': 'https://comicvine.gamespot.com/a/uploads/square_avatar/0/9116/946240-avv.jpg',
    'medium_url': 'https://comicvine.gamespot.com/a/uploads/scale_medium/0/9116/946240-avv.jpg',
    'screen_url': 'https://comicvine.gamespot.com/a/uploads/screen_medium/0/9116/946240-avv.jpg',
    'screen_large_url': 'https://comicvine.gamespot.com/a/uploads/screen_kubrick/0/9116/946240-avv.jpg',
    'small_url': 'https://comicvine.gamespot.com/a/uploads/scale_small/0/9116/946240-avv.jpg',

In [73]:
API_KEY = os.getenv("API_KEY")
BASE_URL = "https://comicvine.gamespot.com/api/"
endpoint = "volumes/"
url = BASE_URL + endpoint

headers = {
    "User-Agent": "absolutePipeline"  
}

all_results = []
offset = 0
limit = 100

while True:
  params = {
        "api_key": API_KEY,
          "format": "json", 
          "filter": "name:Absolute",
          "limit" : limit,
          "offset" : offset
  }

  response = requests.get(url=url, params=params, headers=headers)
  data = response.json()

  results = data['results']
  all_results.extend(results)

  print(f"Fetched {len(results)} records. Total: {len(all_results)}")

  if len(all_results) >= data["number_of_total_results"]:
    break

  offset += limit

print(f"Final count: {len(all_results)}")
print("sample record:")
all_results[-1]

Fetched 100 records. Total: 100
Fetched 72 records. Total: 172
Final count: 172
sample record:

{'aliases': None,
 'api_detail_url': 'https://comicvine.gamespot.com/api/volume/4050-172741/',
 'count_of_issues': 1,
 'date_added': '2026-06-10 00:27:37',
 'date_last_updated': '2026-06-11 02:06:34',
 'deck': ' ',
 'description': '<p>Ongoing series.</p>',
 'first_issue': {'api_detail_url': 'https://comicvine.gamespot.com/api/issue/4000-1170847/',
  'id': 1170847,
  'name': 'The Yarn: Chapter One',
  'issue_number': '1'},
 'id': 172741,
 'image': {'icon_url': 'https://comicvine.gamespot.com/a/uploads/square_avatar/11161/111615891/10093778-cover.jpg',
  'medium_url': 'https://comicvine.gamespot.com/a/uploads/scale_medium/11161/111615891/10093778-cover.jpg',
  'screen_url': 'https://comicvine.gamespot.com/a/uploads/screen_medium/11161/111615891/10093778-cover.jpg',
  'screen_large_url': 'https://comicvine.gamespot.com/a/uploads/screen_kubrick/11161/111615891/10093778-cover.jpg',
  'small_url': 'https://comicvine.gamespot.com/a/uploads/scale_small/11161/111615891/10093778-cover.jpg',
  'super_url': 'https://comicvine.gamespot.com/a/uploads/scale_large/11161/111615891/10093778-cover.jpg',
  'thumb_url': 'https://comicvine.gamespot.com/a/uploads/scale_avatar/11161/111615891/10093778-cover.jpg',
  'tiny_url': 'https://comicvine.gamespot.com/a/uploads/square_mini/11161/111615891/10093778-cover.jpg',
  'original_url': 'https://comicvine.gamespot.com/a/uploads/original/11161/111615891/10093778-cover.jpg',
  'image_tags': 'All Images'},
 'last_issue': {'api_detail_url': 'https://comicvine.gamespot.com/api/issue/4000-1170847/',
  'id': 1170847,
  'name': 'The Yarn: Chapter One',
  'issue_number': '1'},
 'name': 'Absolute Catwoman',
 'publisher': {'api_detail_url': 'https://comicvine.gamespot.com/api/publisher/4010-10/',
  'id': 10,
  'name': 'DC Comics'},
 'site_detail_url': 'https://comicvine.gamespot.com/absolute-catwoman/4050-172741/',
 'start_year': '2026'}

In [74]:
df = pd.json_normalize(all_results)
df.head()

,aliases,api_detail_url,count_of_issues,date_added,date_last_updated,deck,description,id,name,site_detail_url,...,image.tiny_url,image.original_url,image.image_tags,last_issue.api_detail_url,last_issue.id,last_issue.name,last_issue.issue_number,publisher.api_detail_url,publisher.id,publisher.name
0,None,https://comicvine.gamespot.com/api/volume/4050...,4,2008-06-06 11:08:27,2016-12-06 02:32:48,None,<p>It's the return of everyone's favorite horm...,9336,Blue Monday: Absolute Beginners,https://comicvine.gamespot.com/blue-monday-abs...,...,https://comicvine.gamespot.com/a/uploads/squar...,https://comicvine.gamespot.com/a/uploads/origi...,All Images,https://comicvine.gamespot.com/api/issue/4000-...,74774,"Hands Off, She's Mine",4,https://comicvine.gamespot.com/api/publisher/4...,682,Oni Press
1,None,https://comicvine.gamespot.com/api/volume/4050...,1,2008-06-06 11:08:35,2023-05-27 00:27:56,None,<p>Gives a preview of what is coming up in DC ...,18627,Absolute Vertigo,https://comicvine.gamespot.com/absolute-vertig...,...,https://comicvine.gamespot.com/a/uploads/squar...,https://comicvine.gamespot.com/a/uploads/origi...,All Images,https://comicvine.gamespot.com/api/issue/4000-...,109878,Absolute Vertigo,1,https://comicvine.gamespot.com/api/publisher/4...,10,DC Comics
2,None,https://comicvine.gamespot.com/api/volume/4050...,6,2008-08-27 09:20:29,2024-01-15 10:05:59,None,<p>Riiko Izawa has never had a boyfriend and s...,22759,Absolute Boyfriend,https://comicvine.gamespot.com/absolute-boyfri...,...,https://comicvine.gamespot.com/a/uploads/squar...,https://comicvine.gamespot.com/a/uploads/origi...,All Images,https://comicvine.gamespot.com/api/issue/4000-...,136510,Vol. 6,6,https://comicvine.gamespot.com/api/publisher/4...,428,Viz
3,None,https://comicvine.gamespot.com/api/volume/4050...,1,2008-08-27 09:41:09,2020-01-20 19:12:52,None,<p>Deluxe hardcover that collects Batman: The ...,22760,Absolute Dark Knight,https://comicvine.gamespot.com/absolute-dark-k...,...,https://comicvine.gamespot.com/a/uploads/squar...,https://comicvine.gamespot.com/a/uploads/origi...,All Images,https://comicvine.gamespot.com/api/issue/4000-...,136511,Absolute Edition,1,https://comicvine.gamespot.com/api/publisher/4...,10,DC Comics
4,None,https://comicvine.gamespot.com/api/volume/4050...,6,2008-08-27 09:49:50,2014-01-20 04:57:24,None,None,22761,Absolute Zero,https://comicvine.gamespot.com/absolute-zero/4...,...,https://comicvine.gamespot.com/a/uploads/squar...,https://comicvine.gamespot.com/a/uploads/origi...,All Images,https://comicvine.gamespot.com/api/issue/4000-...,136514,None,6,https://comicvine.gamespot.com/api/publisher/4...,488,Antarctic Press

# Volumes Discovery

In [75]:
df[['count_of_issues', 'deck', 'description', 'name','start_year','publisher.name']]

,count_of_issues,deck,description,name,start_year,publisher.name
0,4,None,<p>It's the return of everyone's favorite horm...,Blue Monday: Absolute Beginners,2001,Oni Press
1,1,None,<p>Gives a preview of what is coming up in DC ...,Absolute Vertigo,1995,DC Comics
2,6,None,<p>Riiko Izawa has never had a boyfriend and s...,Absolute Boyfriend,2006,Viz
3,1,None,<p>Deluxe hardcover that collects Batman: The ...,Absolute Dark Knight,2006,DC Comics
4,6,None,None,Absolute Zero,1995,Antarctic Press
...,...,...,...,...,...,...
167,2,None,<p>Spanish publication.</p>,Absolute Martian Manhunter,2025,Panini España
168,2,None,<p>Spanish publication.</p>,Absolute Green Lantern,2025,Panini España
169,1,None,None,Avengers Epic Collection: Absolute Vision,2026,Marvel
170,1,,None,Absolute Green Arrow,2026,DC Comics
171,1,,<p>Ongoing series.</p>,Absolute Catwoman,2026,DC Comics

In [ ]:
df.aliases.value_counts()

aliases
Absolute Batman: The Killing Joke: The 30th Anniversary Edition    1
Absolute Carnage: Weapon +                                         1
アブソリュートキル                                                          1
Name: count, dtype: int64

In [ ]:
df.deck.value_counts()

deck
                                                               59
A set of 3 absolutes of Alan Moore's acclaimed series           1
The absolute collection of the Long Halloween maxi              1
absolute hardcover                                              1
Absolute Batman: Hush                                           1
Absolute DC: The New Frontier                                   1
Absolute Green Lantern: Rebirth                                 1
Absolute Justice                                                1
Absolute Superman for Tomorrow                                  1
The Absolute Authority 1 and 2                                  1
Collects the mini series with the script book                   1
League of Extraordinary Gentlemen Vol. 2: Absolute Edition      1
Omnibus editions of various DCU best sellers in Spanish.        1
Parody collections.                                             1
Published by the French wing of Panini Comics.                  1
                                                                1
                                                                1
Digital Exclusive.                                              1
Name: count, dtype: int64

# Filter volumes from 2024+ and from DC Comics and redundant columns
I filter out Absolute Power volumes because they are a different event, not the Absolute timeline.

In [64]:
df["start_year"] = df["start_year"].astype(int)
df = df[df["start_year"]>=2024]
df[['count_of_issues', 'deck', 'description', 'name','start_year','publisher.name']]

,count_of_issues,deck,description,name,start_year,publisher.name
131,20,None,"<p>Collected in <a href=""/absolute-batman/4050...",Absolute Batman,2024,DC Comics
132,20,None,None,Absolute Wonder Woman,2024,DC Comics
133,19,None,<p>Ongoing series.</p>,Absolute Superman,2025,DC Comics
134,1,None,None,Absolute Batman Noir Edition,2025,DC Comics
135,1,None,None,Absolute Wonder Woman Noir Edition,2025,DC Comics
136,1,None,None,Absolute Superman Noir Edition,2025,DC Comics
137,15,,None,Absolute Flash,2025,DC Comics
138,11,None,None,Absolute Martian Manhunter,2025,DC Comics
139,15,None,None,Absolute Green Lantern,2025,DC Comics
144,1,,None,DC W.I.P.: Absolute Batman 1,2025,DC Comics
145,1,,None,Absolute Evil,2025,DC Comics
146,2,None,"<p>Collected editions of <a href=""/absolute-ba...",Absolute Batman,2025,DC Comics
147,1,None,"<p>Annual for <a href=""/absolute-batman/4050-1...",Absolute Batman 2025 Annual,2025,DC Comics
149,2,,None,Absolute Wonder Woman,2025,DC Comics
150,2,,None,Absolute Superman,2025,DC Comics
151,1,,"<p>Collects <a href=""/absolute-martian-manhunt...",Absolute Martian Manhunter,2025,DC Comics
160,2,,None,Absolute Green Lantern,2025,DC Comics
161,1,,None,Absolute Flash,2025,DC Comics
162,1,None,None,Absolute Batman: Ark-M,2026,DC Comics
164,1,,"<p>Annual for <a href=""/absolute-wonder-woman/...",Absolute Wonder Woman 2026 Annual,2026,DC Comics
170,1,,None,Absolute Green Arrow,2026,DC Comics
171,1,,<p>Ongoing series.</p>,Absolute Catwoman,2026,DC Comics

In [65]:
df = df[df["publisher.name"] == "DC Comics"]
df[['aliases', 'count_of_issues', 'deck', 'description', 'name','start_year','publisher.name']]

,aliases,count_of_issues,deck,description,name,start_year,publisher.name
131,None,20,None,"<p>Collected in <a href=""/absolute-batman/4050...",Absolute Batman,2024,DC Comics
132,None,20,None,None,Absolute Wonder Woman,2024,DC Comics
133,None,19,None,<p>Ongoing series.</p>,Absolute Superman,2025,DC Comics
134,None,1,None,None,Absolute Batman Noir Edition,2025,DC Comics
135,None,1,None,None,Absolute Wonder Woman Noir Edition,2025,DC Comics
136,None,1,None,None,Absolute Superman Noir Edition,2025,DC Comics
137,None,15,,None,Absolute Flash,2025,DC Comics
138,None,11,None,None,Absolute Martian Manhunter,2025,DC Comics
139,None,15,None,None,Absolute Green Lantern,2025,DC Comics
144,None,1,,None,DC W.I.P.: Absolute Batman 1,2025,DC Comics
145,None,1,,None,Absolute Evil,2025,DC Comics
146,None,2,None,"<p>Collected editions of <a href=""/absolute-ba...",Absolute Batman,2025,DC Comics
147,None,1,None,"<p>Annual for <a href=""/absolute-batman/4050-1...",Absolute Batman 2025 Annual,2025,DC Comics
149,None,2,,None,Absolute Wonder Woman,2025,DC Comics
150,None,2,,None,Absolute Superman,2025,DC Comics
151,None,1,,"<p>Collects <a href=""/absolute-martian-manhunt...",Absolute Martian Manhunter,2025,DC Comics
160,None,2,,None,Absolute Green Lantern,2025,DC Comics
161,None,1,,None,Absolute Flash,2025,DC Comics
162,None,1,None,None,Absolute Batman: Ark-M,2026,DC Comics
164,None,1,,"<p>Annual for <a href=""/absolute-wonder-woman/...",Absolute Wonder Woman 2026 Annual,2026,DC Comics
170,None,1,,None,Absolute Green Arrow,2026,DC Comics
171,None,1,,<p>Ongoing series.</p>,Absolute Catwoman,2026,DC Comics

In [66]:
df = df[~df["name"].str.contains("Absolute Power", na=False)]
df[['aliases', 'count_of_issues', 'deck', 'description', 'name','start_year','publisher.name']]

,aliases,count_of_issues,deck,description,name,start_year,publisher.name
131,None,20,None,"<p>Collected in <a href=""/absolute-batman/4050...",Absolute Batman,2024,DC Comics
132,None,20,None,None,Absolute Wonder Woman,2024,DC Comics
133,None,19,None,<p>Ongoing series.</p>,Absolute Superman,2025,DC Comics
134,None,1,None,None,Absolute Batman Noir Edition,2025,DC Comics
135,None,1,None,None,Absolute Wonder Woman Noir Edition,2025,DC Comics
136,None,1,None,None,Absolute Superman Noir Edition,2025,DC Comics
137,None,15,,None,Absolute Flash,2025,DC Comics
138,None,11,None,None,Absolute Martian Manhunter,2025,DC Comics
139,None,15,None,None,Absolute Green Lantern,2025,DC Comics
144,None,1,,None,DC W.I.P.: Absolute Batman 1,2025,DC Comics
145,None,1,,None,Absolute Evil,2025,DC Comics
146,None,2,None,"<p>Collected editions of <a href=""/absolute-ba...",Absolute Batman,2025,DC Comics
147,None,1,None,"<p>Annual for <a href=""/absolute-batman/4050-1...",Absolute Batman 2025 Annual,2025,DC Comics
149,None,2,,None,Absolute Wonder Woman,2025,DC Comics
150,None,2,,None,Absolute Superman,2025,DC Comics
151,None,1,,"<p>Collects <a href=""/absolute-martian-manhunt...",Absolute Martian Manhunter,2025,DC Comics
160,None,2,,None,Absolute Green Lantern,2025,DC Comics
161,None,1,,None,Absolute Flash,2025,DC Comics
162,None,1,None,None,Absolute Batman: Ark-M,2026,DC Comics
164,None,1,,"<p>Annual for <a href=""/absolute-wonder-woman/...",Absolute Wonder Woman 2026 Annual,2026,DC Comics
170,None,1,,None,Absolute Green Arrow,2026,DC Comics
171,None,1,,<p>Ongoing series.</p>,Absolute Catwoman,2026,DC Comics

In [70]:
df = df[['api_detail_url', 'count_of_issues', 'date_added',
       'date_last_updated', 'description', 'id', 'name',
       'site_detail_url', 'start_year', 'first_issue.api_detail_url',
       'first_issue.id', 'first_issue.name', 'first_issue.issue_number',
       'image.medium_url','last_issue.api_detail_url', 'last_issue.id',
       'last_issue.name', 'last_issue.issue_number',
       'publisher.api_detail_url', 'publisher.id', 'publisher.name']]
df

,api_detail_url,count_of_issues,date_added,date_last_updated,description,id,name,site_detail_url,start_year,first_issue.api_detail_url,...,first_issue.name,first_issue.issue_number,image.medium_url,last_issue.api_detail_url,last_issue.id,last_issue.name,last_issue.issue_number,publisher.api_detail_url,publisher.id,publisher.name
131,https://comicvine.gamespot.com/api/volume/4050...,20,2024-10-07 06:21:22,2025-10-25 20:28:42,"<p>Collected in <a href=""/absolute-batman/4050...",160294,Absolute Batman,https://comicvine.gamespot.com/absolute-batman...,2024,https://comicvine.gamespot.com/api/issue/4000-...,...,"The Zoo, Part One",1,https://comicvine.gamespot.com/a/uploads/scale...,https://comicvine.gamespot.com/api/issue/4000-...,1166236,The Straw Man,20,https://comicvine.gamespot.com/api/publisher/4...,10,DC Comics
132,https://comicvine.gamespot.com/api/volume/4050...,20,2024-10-21 07:02:31,2024-10-21 07:02:49,None,160511,Absolute Wonder Woman,https://comicvine.gamespot.com/absolute-wonder...,2024,https://comicvine.gamespot.com/api/issue/4000-...,...,"The Last Amazon, Part 1 of 5",1,https://comicvine.gamespot.com/a/uploads/scale...,https://comicvine.gamespot.com/api/issue/4000-...,1168224,"Season of the Witch, Part 5 of 5",20,https://comicvine.gamespot.com/api/publisher/4...,10,DC Comics
133,https://comicvine.gamespot.com/api/volume/4050...,19,2024-11-04 11:16:32,2026-01-30 09:59:34,<p>Ongoing series.</p>,160860,Absolute Superman,https://comicvine.gamespot.com/absolute-superm...,2025,https://comicvine.gamespot.com/api/issue/4000-...,...,Last Dust of Krypton - Part One: Down in the Dirt,1,https://comicvine.gamespot.com/a/uploads/scale...,https://comicvine.gamespot.com/api/issue/4000-...,1165103,"Reign of the Superman, Part Two: Red Steel in ...",19,https://comicvine.gamespot.com/api/publisher/4...,10,DC Comics
134,https://comicvine.gamespot.com/api/volume/4050...,1,2024-11-11 10:24:38,2024-11-11 10:24:53,None,161010,Absolute Batman Noir Edition,https://comicvine.gamespot.com/absolute-batman...,2025,https://comicvine.gamespot.com/api/issue/4000-...,...,None,1,https://comicvine.gamespot.com/a/uploads/scale...,https://comicvine.gamespot.com/api/issue/4000-...,1077466,None,1,https://comicvine.gamespot.com/api/publisher/4...,10,DC Comics
135,https://comicvine.gamespot.com/api/volume/4050...,1,2024-11-25 09:54:10,2024-11-25 09:54:30,None,161308,Absolute Wonder Woman Noir Edition,https://comicvine.gamespot.com/absolute-wonder...,2025,https://comicvine.gamespot.com/api/issue/4000-...,...,None,1,https://comicvine.gamespot.com/a/uploads/scale...,https://comicvine.gamespot.com/api/issue/4000-...,1079211,None,1,https://comicvine.gamespot.com/api/publisher/4...,10,DC Comics
136,https://comicvine.gamespot.com/api/volume/4050...,1,2024-12-02 14:50:30,2024-12-02 14:50:44,None,161397,Absolute Superman Noir Edition,https://comicvine.gamespot.com/absolute-superm...,2025,https://comicvine.gamespot.com/api/issue/4000-...,...,None,1,https://comicvine.gamespot.com/a/uploads/scale...,https://comicvine.gamespot.com/api/issue/4000-...,1080070,None,1,https://comicvine.gamespot.com/api/publisher/4...,10,DC Comics
137,https://comicvine.gamespot.com/api/volume/4050...,15,2025-03-18 20:48:26,2025-03-19 03:03:10,None,162847,Absolute Flash,https://comicvine.gamespot.com/absolute-flash/...,2025,https://comicvine.gamespot.com/api/issue/4000-...,...,"Of Two Worlds, Part One",1,https://comicvine.gamespot.com/a/uploads/scale...,https://comicvine.gamespot.com/api/issue/4000-...,1167127,...Of Things to Come,15,https://comicvine.gamespot.com/api/publisher/4...,10,DC Comics
138,https://comicvine.gamespot.com/api/volume/4050...,11,2025-03-23 17:51:56,2025-03-23 17:52:12,None,162966,Absolute Martian Manhunter,https://comicvine.gamespot.com/absolute-martia...,2025,https://comicvine.gamespot.com/api/issue/4000-...,...,None,1,https://comicvine.gamespot.com/a/uploads/scale...,https://comicvine.gamespot.com/api/issue/4000-...,1166237,None,11,https://comicvine.gamespot.com/api/publisher/4...,10,DC Comics
139,https://comicvine.gamespot.com/api/volume/4050...,15,2025-04-01 10:54:17,2025-04-01 10:54:35,None,163145,Absolute Green Lantern,https://comicvine.gamespot.com/absolute-green-...,2025,https://comicvine.gamespot.com/api/issue/4000-...,...,Episode One: The Black Hand,1,https://comicvine.gamespot.com/a/uploads/scale...,https://comicvine.gamespot.com/api/issue/4000-...,1169578,Episode Fifteen: Power Struggle,15,https://comicvine.gamespot.com/api/publisher/4...,10,DC Comics
144,https://comicvine.gamespot.com/api/volume/4050...,1,2025-09-17 01:08:53,2025-09-17 03:42:39,None,167085,DC W.I.P.: Absolute Batman 1,https://comicvine.gamespot.com/dc-wip-absolute...,2025,https://comicvine.gamespot.com/api/issue/4000-...,...,None,1,https://comicvine.gamespot.com/a/uploads/scale...,https://comicvine.gamespot.com/api/issue/4000-...,1133800,None,1,https://comicvine.gamespot.com/api/publisher/4...,10,DC Comics
145,https://comicvine.gamespot.com/api/volume/4050...,1,2025-10-01 00:43:07,2025-10-01 03:26:07,None,167313,Absolute Evil,https://comicvine.gamespot.com/absolute-evil/4...,2025,https://comicvine.gamespot.com/api/issue/4000-...,...,Absolute Justice,1,https://comicvine.gamespot.com/a/uploads/scale...,https://comicvine.gamespot.com/api/issue/4000-...,1136070,Absolute Justice,1,https://comicvine.gamespot.com/api/publisher/4...,10,DC Comics
146,https://comicvine.gamespot.com/api/volume/4050...,2,2025-10-01 09:31:41,2025-10-23 05:48:09,"<p>Collected editions of <a href=""/absolute-ba...",167340,Absolute Batman,https://comicvine.gamespot.com/absolute-batman...,2025,https://comicvine.gamespot.com/api/issue/4000-...,...,Vol. 1: The Zoo,1,https://comicvine.gamespot.com/a/uploads/scale...,https://comicvine.gamespot.com/api/issue/4000-...,1155343,Vol. 2: Abomination,2,https://comicvine.gamespot.com/api/publisher/4...,10,DC Comics
147,https://comicvine.gamespot.com/api/volume/4050...,1,2025-10-28 07:54:15,2026-04-24 07:11:51,"<p>Annual for <a href=""/absolute-batman/4050-1...",168013,Absolute Batman 2025 Annual,https://comicvine.gamespot.com/absolute-batman...,2025,https://comicvine.gamespot.com/api/issue/4000-...,...,[Untitled]; Sanctuary; Let's Learn About Bats!,1,https://comicvine.gamespot.com/a/uploads/scale...,https://comicvine.gamespot.com/api/issue/4000-...,1140600,[Untitled]; Sanctuary; Let's Learn About Bats!,1,https://comicvine.gamespot.com/api/publisher/4...,10,DC Comics
149,https://comicvine.gamespot.com/api/volume/4050...,2,2025-11-18 23:31:29,2025-12-04 13:07:30,None,168588,Absolute Wonder Woman,https://comicvine.gamespot.com/absolute-wonder...,2025,https://comicvine.gamespot.com/api/issue/4000-...,...,Vol. 1: The Last Amazon,1,https://comicvine.gamespot.com/a/uploads/scale...,https://comicvine.gamespot.com/api/issue/4000-...,1156259,Vol. 2: As My Mothers Made Me,2,https://comicvine.gamespot.com/api/publisher/4...,10,DC Comics
150,https://comicvine.gamespot.com/api/volume/4050...,2,2025-11-18 23:33:59,2025-12-04 13:07:23,None,168589,Absolute Superman,https://comicvine.gamespot.com/absolute-superm...,2025,https://comicvine.gamespot.com/api/issue/4000-...,...,Vol. 1: Last Dust of Krypton,1,https://comicvine.gamespot.com/a/uploads/scale...,https://comicvine.gamespot.com/api/issue/4000-...,1158289,Vol. 2: Son of the Demon,2,https://comicvine.gamespot.com/api/publisher/4...,10,DC Comics
151,https://comicvine.gamespot.com/api/volume/4050...,1,2025-11-18 23:36:53,2026-01-24 15:40:23,"<p>Collects <a href=""/absolute-martian-manhunt...",168590,Absolute Martian Manhunter,https://comicvine.gamespot.com/absolute-martia...,2025,https://comicvine.gamespot.com/api/issue/4000-...,...,Vol. 1: Martian Vision,1,https://comicvine.gamespot.com/a/uploads/scale...,https://comicvine.gamespot.com/api/issue/4000-...,1144216,Vol. 1: Martian Vision,1,https://comicvine.gamespot.com/api/publisher/4...,10,DC Comics
160,https://comicvine.gamespot.com/api/volume/4050...,2,2025-12-10 00:35:22,2025-12-10 03:30:45,None,169121,Absolute Green Lantern,https://comicvine.gamespot.com/absolute-green-...,2025,https://comicvine.gamespot.com/api/issue/4000-...,...,None,1,https://comicvine.gamespot.com/a/uploads/scale...,https://comicvine.gamespot.com/api/issue/4000-...,1170848,Vol. 2: Sojourner,2,https://comicvine.gamespot.com/api/publisher/4...,10,DC Comics
161,https://comicvine.gamespot.com/api/volume/4050...,1,2025-12-24 00:10:35,2026-04-08 00:18:30,None,169521,Absolute Flash,https://comicvine.gamespot.com/absolute-flash/...,2025,https://comicvine.gamespot.com/api/issue/4000-...,...,None,1,https://comicvine.gamespot.com/a/uploads/scale...,https://comicvine.gamespot.com/api/issue/4000-...,1149825,None,1,https://comicvine.gamespot.com/api/publisher/4...,10,DC Comics
162,https://comicvine.gamespot.com/api/volume/4050...,1,2026-01-06 19:44:46,2026-01-07 13:01:48,None,169970,Absolute Batman: Ark-M,https://comicvine.gamespot.com/absolute-batman...,2026,https://comicvine.gamespot.com/api/issue/4000-...,...,A History of Arkham,1,https://comicvine.gamespot.com/a/uploads/scale...,https://comicvine.gamespot.com/api/issue/4000-...,1151955,A History of Arkham,1,https://comicvine.gamespot.com/api/publisher/4...,10,DC Comics
164,https://comicvine.gamespot.com/api/volume/4050...,1,2026-02-11 01:03:33,2026-04-24 07:11:58,"<p>Annual for <a href=""/absolute-wonder-woman/...",170538,Absolute Wonder Woman 2026 Annual,https://comicvine.gamespot.com/absolute-wonder...,2026,https://comicvine.gamespot.com/api/issue/4000-...,...,Cursing and Cursed,1,https://comicvine.gamespot.com/a/uploads/scale...,https://comicvine.gamespot.com/api/issue/4000-...,1155837,Cursing and Cursed,1,https://comicvine.gamespot.com/api/publisher/4...,10,DC Comics
170,https://comicvine.gamespot.com/api/volume/4050...,1,2026-05-20 00:17:06,2026-05-20 04:12:42,None,172003,Absolute Green Arrow,https://comicvine.gamespot.com/absolute-green-...,2026,https://comicvine.gamespot.com/api/issue/4000-...,...,"The Longbow Killer, Chapter 1",1,https://comicvine.gamespot.com/a/uploads/scale...,https://comicvine.gamespot.com/api/issue/4000-...,1167128,"The Longbow Killer, Chapter 1",1,https://comicvine.gamespot.com/api/publisher/4...,10,DC Comics
171,https://comicvine.gamespot.com/api/volume/4050...,1,2026-06-10 00:27:37,2026-06-11 02:06:34,<p>Ongoing series.</p>,172741,Absolute Catwoman,https://comicvine.gamespot.com/absolute-catwom...,2026,https://comicvine.gamespot.com/api/issue/4000-...,...,The Yarn: Chapter One,1,https://comicvine.gamespot.com/a/uploads/scale...,https://comicvine.gamespot.com/api/issue/4000-...,1170847,The Yarn: Chapter One,1,https://comicvine.gamespot.com/api/publisher/4...,10,DC Comics

In [69]:
all_results[-1]

{'aliases': None,
 'api_detail_url': 'https://comicvine.gamespot.com/api/volume/4050-172741/',
 'count_of_issues': 1,
 'date_added': '2026-06-10 00:27:37',
 'date_last_updated': '2026-06-11 02:06:34',
 'deck': ' ',
 'description': '<p>Ongoing series.</p>',
 'first_issue': {'api_detail_url': 'https://comicvine.gamespot.com/api/issue/4000-1170847/',
  'id': 1170847,
  'name': 'The Yarn: Chapter One',
  'issue_number': '1'},
 'id': 172741,
 'image': {'icon_url': 'https://comicvine.gamespot.com/a/uploads/square_avatar/11161/111615891/10093778-cover.jpg',
  'medium_url': 'https://comicvine.gamespot.com/a/uploads/scale_medium/11161/111615891/10093778-cover.jpg',
  'screen_url': 'https://comicvine.gamespot.com/a/uploads/screen_medium/11161/111615891/10093778-cover.jpg',
  'screen_large_url': 'https://comicvine.gamespot.com/a/uploads/screen_kubrick/11161/111615891/10093778-cover.jpg',
  'small_url': 'https://comicvine.gamespot.com/a/uploads/scale_small/11161/111615891/10093778-cover.jpg',
  'super_url': 'https://comicvine.gamespot.com/a/uploads/scale_large/11161/111615891/10093778-cover.jpg',
  'thumb_url': 'https://comicvine.gamespot.com/a/uploads/scale_avatar/11161/111615891/10093778-cover.jpg',
  'tiny_url': 'https://comicvine.gamespot.com/a/uploads/square_mini/11161/111615891/10093778-cover.jpg',
  'original_url': 'https://comicvine.gamespot.com/a/uploads/original/11161/111615891/10093778-cover.jpg',
  'image_tags': 'All Images'},
 'last_issue': {'api_detail_url': 'https://comicvine.gamespot.com/api/issue/4000-1170847/',
  'id': 1170847,
  'name': 'The Yarn: Chapter One',
  'issue_number': '1'},
 'name': 'Absolute Catwoman',
 'publisher': {'api_detail_url': 'https://comicvine.gamespot.com/api/publisher/4010-10/',
  'id': 10,
  'name': 'DC Comics'},
 'site_detail_url': 'https://comicvine.gamespot.com/absolute-catwoman/4050-172741/',
 'start_year': '2026'}

In [ ]:
df[['aliases', 'api_detail_url', 'count_of_issues', 'date_added',
       'date_last_updated', 'deck', 'description', 'id', 'name',
       'site_detail_url', 'start_year', 'first_issue.api_detail_url',
       'first_issue.id', 'first_issue.name', 'first_issue.issue_number',
       'image.medium_url','last_issue.api_detail_url', 'last_issue.id',
       'last_issue.name', 'last_issue.issue_number',
       'publisher.api_detail_url', 'publisher.id', 'publisher.name']]

In [67]:
df.to_csv("results.csv")