In [1]:
import requests
from dotenv import load_dotenv
import os
import json
import pandas as pd
import time

load_dotenv()

True

In [2]:
volumes = pd.read_csv("volumes.csv")
volumes.head()

,api_detail_url,count_of_issues,date_added,date_last_updated,description,id,name,site_detail_url,start_year,first_issue_api_detail_url,...,first_issue_name,first_issue_issue_number,image_medium_url,last_issue_api_detail_url,last_issue_id,last_issue_name,last_issue_issue_number,publisher_api_detail_url,publisher_id,publisher_name
0,https://comicvine.gamespot.com/api/volume/4050...,20,2024-10-07 06:21:22,2025-10-25 20:28:42,"<p>Collected in <a href=""/absolute-batman/4050...",160294,Absolute Batman,https://comicvine.gamespot.com/absolute-batman...,2024,https://comicvine.gamespot.com/api/issue/4000-...,...,"The Zoo, Part One",1,https://comicvine.gamespot.com/a/uploads/scale...,https://comicvine.gamespot.com/api/issue/4000-...,1166236,The Straw Man,20,https://comicvine.gamespot.com/api/publisher/4...,10,DC Comics
1,https://comicvine.gamespot.com/api/volume/4050...,20,2024-10-21 07:02:31,2024-10-21 07:02:49,NaN,160511,Absolute Wonder Woman,https://comicvine.gamespot.com/absolute-wonder...,2024,https://comicvine.gamespot.com/api/issue/4000-...,...,"The Last Amazon, Part 1 of 5",1,https://comicvine.gamespot.com/a/uploads/scale...,https://comicvine.gamespot.com/api/issue/4000-...,1168224,"Season of the Witch, Part 5 of 5",20,https://comicvine.gamespot.com/api/publisher/4...,10,DC Comics
2,https://comicvine.gamespot.com/api/volume/4050...,19,2024-11-04 11:16:32,2026-01-30 09:59:34,<p>Ongoing series.</p>,160860,Absolute Superman,https://comicvine.gamespot.com/absolute-superm...,2025,https://comicvine.gamespot.com/api/issue/4000-...,...,Last Dust of Krypton - Part One: Down in the Dirt,1,https://comicvine.gamespot.com/a/uploads/scale...,https://comicvine.gamespot.com/api/issue/4000-...,1165103,"Reign of the Superman, Part Two: Red Steel in ...",19,https://comicvine.gamespot.com/api/publisher/4...,10,DC Comics
3,https://comicvine.gamespot.com/api/volume/4050...,1,2024-11-11 10:24:38,2024-11-11 10:24:53,NaN,161010,Absolute Batman Noir Edition,https://comicvine.gamespot.com/absolute-batman...,2025,https://comicvine.gamespot.com/api/issue/4000-...,...,NaN,1,https://comicvine.gamespot.com/a/uploads/scale...,https://comicvine.gamespot.com/api/issue/4000-...,1077466,NaN,1,https://comicvine.gamespot.com/api/publisher/4...,10,DC Comics
4,https://comicvine.gamespot.com/api/volume/4050...,1,2024-11-25 09:54:10,2024-11-25 09:54:30,NaN,161308,Absolute Wonder Woman Noir Edition,https://comicvine.gamespot.com/absolute-wonder...,2025,https://comicvine.gamespot.com/api/issue/4000-...,...,NaN,1,https://comicvine.gamespot.com/a/uploads/scale...,https://comicvine.gamespot.com/api/issue/4000-...,1079211,NaN,1,https://comicvine.gamespot.com/api/publisher/4...,10,DC Comics

In [ ]:
API_KEY = os.getenv("API_KEY")
headers = {
    "User-Agent": "absolutePipeline"  
}
params = {
        "api_key": API_KEY,
        "format": "json", 
        "field_list": "issues"
}

all_issues_df = pd.DataFrame(columns=["api_detail_url",	"id",	"name",	"site_detail_url",	"issue_number"])

for row in volumes.itertuples(): 
    print(f"{row.Index} getting issues of {row.name} at {row.api_detail_url}...")
    volume_api_url = row.api_detail_url
    response = requests.get(url=volume_api_url, params=params, headers=headers)
    data= response.json()
    issues = data["results"]["issues"]
    issues_df = pd.DataFrame(issues)
    all_issues_df = pd.concat([all_issues_df, issues_df], ignore_index=True)
    if row.Index == 1:
        break

all_issues_df

0 getting issues of Absolute Batman at https://comicvine.gamespot.com/api/volume/4050-160294/...
1 getting issues of Absolute Wonder Woman at https://comicvine.gamespot.com/api/volume/4050-160511/...

,api_detail_url,id,name,site_detail_url,issue_number
0,https://comicvine.gamespot.com/api/issue/4000-...,1073108,"The Zoo, Part One",https://comicvine.gamespot.com/absolute-batman...,1
1,https://comicvine.gamespot.com/api/issue/4000-...,1077465,"The Zoo, Part Two",https://comicvine.gamespot.com/absolute-batman...,2
2,https://comicvine.gamespot.com/api/issue/4000-...,1083601,"The Zoo, Part Three",https://comicvine.gamespot.com/absolute-batman...,3
3,https://comicvine.gamespot.com/api/issue/4000-...,1089295,"The Zoo, Part Four",https://comicvine.gamespot.com/absolute-batman...,4
4,https://comicvine.gamespot.com/api/issue/4000-...,1095530,"The Zoo, Part Five",https://comicvine.gamespot.com/absolute-batman...,5
5,https://comicvine.gamespot.com/api/issue/4000-...,1099460,"The Zoo, Part Six",https://comicvine.gamespot.com/absolute-batman...,6
6,https://comicvine.gamespot.com/api/issue/4000-...,1102449,Absolute Zero,https://comicvine.gamespot.com/absolute-batman...,7
7,https://comicvine.gamespot.com/api/issue/4000-...,1109522,Absolute Zero,https://comicvine.gamespot.com/absolute-batman...,8
8,https://comicvine.gamespot.com/api/issue/4000-...,1115570,"Abomination, Part One",https://comicvine.gamespot.com/absolute-batman...,9
9,https://comicvine.gamespot.com/api/issue/4000-...,1120416,"Abomination, Part Two",https://comicvine.gamespot.com/absolute-batman...,10
10,https://comicvine.gamespot.com/api/issue/4000-...,1126983,"Abomination, Part Three",https://comicvine.gamespot.com/absolute-batman...,11
11,https://comicvine.gamespot.com/api/issue/4000-...,1131749,"Abomination, Part Four",https://comicvine.gamespot.com/absolute-batman...,12
12,https://comicvine.gamespot.com/api/issue/4000-...,1137116,"Abomination, Part Five",https://comicvine.gamespot.com/absolute-batman...,13
13,https://comicvine.gamespot.com/api/issue/4000-...,1145497,"Abomination, Conclusion",https://comicvine.gamespot.com/absolute-batman...,14
14,https://comicvine.gamespot.com/api/issue/4000-...,1147554,The Joker,https://comicvine.gamespot.com/absolute-batman...,15
15,https://comicvine.gamespot.com/api/issue/4000-...,1154054,Bat Out of Hell,https://comicvine.gamespot.com/absolute-batman...,16
16,https://comicvine.gamespot.com/api/issue/4000-...,1156258,The Seventh Kingdom - Part 1,https://comicvine.gamespot.com/absolute-batman...,17
17,https://comicvine.gamespot.com/api/issue/4000-...,1158997,The Seventh Kingdom - Part 2,https://comicvine.gamespot.com/absolute-batman...,18
18,https://comicvine.gamespot.com/api/issue/4000-...,1163009,The Straw Man,https://comicvine.gamespot.com/absolute-batman...,19
19,https://comicvine.gamespot.com/api/issue/4000-...,1166236,The Straw Man,https://comicvine.gamespot.com/absolute-batman...,20
20,https://comicvine.gamespot.com/api/issue/4000-...,1074563,"The Last Amazon, Part 1 of 5",https://comicvine.gamespot.com/absolute-wonder...,1
21,https://comicvine.gamespot.com/api/issue/4000-...,1079209,"The Last Amazon, Part 2 of 5",https://comicvine.gamespot.com/absolute-wonder...,2
22,https://comicvine.gamespot.com/api/issue/4000-...,1085923,"The Last Amazon, Part 3 of 5",https://comicvine.gamespot.com/absolute-wonder...,3
23,https://comicvine.gamespot.com/api/issue/4000-...,1090802,"The Last Amazon, Part 4 of 5",https://comicvine.gamespot.com/absolute-wonder...,4
24,https://comicvine.gamespot.com/api/issue/4000-...,1096891,"The Last Amazon, Part 5 of 5",https://comicvine.gamespot.com/absolute-wonder...,5
25,https://comicvine.gamespot.com/api/issue/4000-...,1100111,"The Lady or the Tiger, Part 1; Li'l Diana",https://comicvine.gamespot.com/absolute-wonder...,6
26,https://comicvine.gamespot.com/api/issue/4000-...,1106021,"The Lady or the Tiger, Part 2; Li'l Diana",https://comicvine.gamespot.com/absolute-wonder...,7
27,https://comicvine.gamespot.com/api/issue/4000-...,1112938,"As My Mothers Made Me, Part 1",https://comicvine.gamespot.com/absolute-wonder...,8
28,https://comicvine.gamespot.com/api/issue/4000-...,1116606,"As My Mothers Made Me, Part 2 of 5",https://comicvine.gamespot.com/absolute-wonder...,9
29,https://comicvine.gamespot.com/api/issue/4000-...,1121439,As My Mothers Made Me. Part 3 of 5,https://comicvine.gamespot.com/absolute-wonder...,10
30,https://comicvine.gamespot.com/api/issue/4000-...,1128888,"As My Mothers Made Me, Part 4 of 5",https://comicvine.gamespot.com/absolute-wonder...,11
31,https://comicvine.gamespot.com/api/issue/4000-...,1134428,"As My Mothers Made Me, Part 5 of 5",https://comicvine.gamespot.com/absolute-wonder...,12
32,https://comicvine.gamespot.com/api/issue/4000-...,1139062,"The Price, Part 1 of 2",https://comicvine.gamespot.com/absolute-wonder...,13
33,https://comicvine.gamespot.com/api/issue/4000-...,1145498,"The Price, Part 2 of 2",https://comicvine.gamespot.com/absolute-wonder...,14
34,https://comicvine.gamespot.com/api/issue/4000-...,1149795,The Mark of Hecate,https://comicvine.gamespot.com/absolute-wonder...,15
35,https://comicvine.gamespot.com/api/issue/4000-...,1154057,"Season of the Witch, Part 1 of 5",https://comicvine.gamespot.com/absolute-wonder...,16
36,https://comicvine.gamespot.com/api/issue/4000-...,1156913,"Season of the Witch, Part 2 of 5",https://comicvine.gamespot.com/absolute-wonder...,17
37,https://comicvine.gamespot.com/api/issue/4000-...,1160262,"Season of the Witch, Part 3 of 5",https://comicvine.gamespot.com/absolute-wonder...,18
38,https://comicvine.gamespot.com/api/issue/4000-...,1163573,"Season of the Witch, Part 4 of 5",https://comicvine.gamespot.com/absolute-wonder...,19
39,https://comicvine.gamespot.com/api/issue/4000-...,1168224,"Season of the Witch, Part 5 of 5",https://comicvine.gamespot.com/absolute-wonder...,20

In [12]:
params = {
        "api_key": API_KEY,
        "format": "json", 
        "field_list": ["date_last_updated,character_credits,description,id,image,object_credits,person_credits,store_date,volume"]
}


for col in ["characters", "objects", "colorists", "artists", "writers"]:
    all_issues_df[col] = None
for row in all_issues_df.itertuples():
    print(f"{row.Index} getting data of issue {row.name} at {row.api_detail_url}...")
    issue_url = all_issues_df['api_detail_url'][row.Index]

    response = requests.get(url=issue_url, params=params, headers=headers)
    data = response.json()

    characters_json = data["results"]["character_credits"]
    characters_list = []
    for character in characters_json: 
        characters_list.append(character.get("name"))

    description= data["results"]["description"]

    image_url = data["results"]["image"]["medium_url"]

    objects_json = data["results"]["object_credits"]
    objects_list = []
    for object in objects_json: 
        objects_list.append(object.get("name"))
   
    persons_json = data["results"]["person_credits"] 
    for person in persons_json: 
        colorists = [p["name"] for p in persons_json if "colorist" in p.get("role", "")]
        artists = [p["name"] for p in persons_json if "artist" in p.get("role", "")]
        writers = [p["name"] for p in persons_json if "writer" in p.get("role", "")]
    
    store_date = data["results"]["store_date"] 
    volume_id = data["results"]["volume"]["id"]

    all_issues_df.at[row.Index, "characters"] = characters_list
    all_issues_df.at[row.Index, "description"] = description
    all_issues_df.at[row.Index, "image_url"] = image_url
    all_issues_df.at[row.Index, "objects"] = objects_list
    all_issues_df.at[row.Index, "colorists"] = colorists
    all_issues_df.at[row.Index, "artists"] = artists
    all_issues_df.at[row.Index, "writers"] = writers
    all_issues_df.at[row.Index, "store_date"] = store_date
    all_issues_df.at[row.Index, "volume_id"] = int(volume_id)

    time.sleep(5)

for col in ["characters", "objects", "colorists", "artists", "writers"]:
    all_issues_df[col] = all_issues_df[col].apply(
        lambda x: ", ".join(x) if isinstance(x, list) else x
    )

all_issues_df

0 getting data of issue The Zoo, Part One at https://comicvine.gamespot.com/api/issue/4000-1073108/...
1 getting data of issue The Zoo, Part Two at https://comicvine.gamespot.com/api/issue/4000-1077465/...
2 getting data of issue The Zoo, Part Three at https://comicvine.gamespot.com/api/issue/4000-1083601/...
3 getting data of issue The Zoo, Part Four at https://comicvine.gamespot.com/api/issue/4000-1089295/...
4 getting data of issue The Zoo, Part Five at https://comicvine.gamespot.com/api/issue/4000-1095530/...
5 getting data of issue The Zoo, Part Six at https://comicvine.gamespot.com/api/issue/4000-1099460/...
6 getting data of issue Absolute Zero at https://comicvine.gamespot.com/api/issue/4000-1102449/...
7 getting data of issue Absolute Zero at https://comicvine.gamespot.com/api/issue/4000-1109522/...
8 getting data of issue Abomination, Part One at https://comicvine.gamespot.com/api/issue/4000-1115570/...
9 getting data of issue Abomination, Part Two at https://comicvine.gamespot.com/api/issue/4000-1120416/...
10 getting data of issue Abomination, Part Three at https://comicvine.gamespot.com/api/issue/4000-1126983/...
11 getting data of issue Abomination, Part Four at https://comicvine.gamespot.com/api/issue/4000-1131749/...
12 getting data of issue Abomination, Part Five at https://comicvine.gamespot.com/api/issue/4000-1137116/...
13 getting data of issue Abomination, Conclusion at https://comicvine.gamespot.com/api/issue/4000-1145497/...
14 getting data of issue The Joker at https://comicvine.gamespot.com/api/issue/4000-1147554/...
15 getting data of issue Bat Out of Hell at https://comicvine.gamespot.com/api/issue/4000-1154054/...
16 getting data of issue The Seventh Kingdom - Part 1 at https://comicvine.gamespot.com/api/issue/4000-1156258/...
17 getting data of issue The Seventh Kingdom - Part 2 at https://comicvine.gamespot.com/api/issue/4000-1158997/...
18 getting data of issue The Straw Man at https://comicvine.gamespot.com/api/issue/4000-1163009/...
19 getting data of issue The Straw Man at https://comicvine.gamespot.com/api/issue/4000-1166236/...
20 getting data of issue The Last Amazon, Part 1 of 5 at https://comicvine.gamespot.com/api/issue/4000-1074563/...
21 getting data of issue The Last Amazon, Part 2 of 5 at https://comicvine.gamespot.com/api/issue/4000-1079209/...
22 getting data of issue The Last Amazon, Part 3 of 5 at https://comicvine.gamespot.com/api/issue/4000-1085923/...
23 getting data of issue The Last Amazon, Part 4 of 5 at https://comicvine.gamespot.com/api/issue/4000-1090802/...
24 getting data of issue The Last Amazon, Part 5 of 5 at https://comicvine.gamespot.com/api/issue/4000-1096891/...
25 getting data of issue The Lady or the Tiger, Part 1; Li'l Diana at https://comicvine.gamespot.com/api/issue/4000-1100111/...
26 getting data of issue The Lady or the Tiger, Part 2; Li'l Diana at https://comicvine.gamespot.com/api/issue/4000-1106021/...
27 getting data of issue As My Mothers Made Me, Part 1 at https://comicvine.gamespot.com/api/issue/4000-1112938/...
28 getting data of issue As My Mothers Made Me, Part 2 of 5 at https://comicvine.gamespot.com/api/issue/4000-1116606/...
29 getting data of issue As My Mothers Made Me. Part 3 of 5 at https://comicvine.gamespot.com/api/issue/4000-1121439/...
30 getting data of issue As My Mothers Made Me, Part 4 of 5 at https://comicvine.gamespot.com/api/issue/4000-1128888/...
31 getting data of issue As My Mothers Made Me, Part 5 of 5 at https://comicvine.gamespot.com/api/issue/4000-1134428/...
32 getting data of issue The Price, Part 1 of 2 at https://comicvine.gamespot.com/api/issue/4000-1139062/...
33 getting data of issue The Price, Part 2 of 2 at https://comicvine.gamespot.com/api/issue/4000-1145498/...
34 getting data of issue The Mark of Hecate at https://comicvine.gamespot.com/api/issue/4000-1149795/...
35 getting data of issue Season of the Witch, Part 1 of 5 at https://comicvine.gamespot.com/api/issue/4000-1154057/...
36 getting data of issue Season of the Witch, Part 2 of 5 at https://comicvine.gamespot.com/api/issue/4000-1156913/...
37 getting data of issue Season of the Witch, Part 3 of 5 at https://comicvine.gamespot.com/api/issue/4000-1160262/...
38 getting data of issue Season of the Witch, Part 4 of 5 at https://comicvine.gamespot.com/api/issue/4000-1163573/...
39 getting data of issue Season of the Witch, Part 5 of 5 at https://comicvine.gamespot.com/api/issue/4000-1168224/...

,api_detail_url,id,name,site_detail_url,issue_number,characters,objects,colorists,artists,writers,description,image_url,store_date,volume_id
0,https://comicvine.gamespot.com/api/issue/4000-...,1073108,"The Zoo, Part One",https://comicvine.gamespot.com/absolute-batman...,1,"Alfred Pennyworth, Barbara Gordon, Batman, Bla...","Bat-Suit, Batmobile, Utility Belt",Frank Martin Jr.,Nick Dragotta,Scott Snyder,<p><em><b>BATMAN LEGEND SCOTT SNYDER AND ICONI...,https://comicvine.gamespot.com/a/uploads/scale...,2024-10-09,160294.0
1,https://comicvine.gamespot.com/api/issue/4000-...,1077465,"The Zoo, Part Two",https://comicvine.gamespot.com/absolute-batman...,2,"Alfred Pennyworth, Barbara Gordon, Batman, Bla...","Bat-Suit, Batmobile",Frank Martin Jr.,Nick Dragotta,Scott Snyder,<p><em><b>SNYDER AND DRAGOTTA'S BRAND-NEW TAKE...,https://comicvine.gamespot.com/a/uploads/scale...,2024-11-13,160294.0
2,https://comicvine.gamespot.com/api/issue/4000-...,1083601,"The Zoo, Part Three",https://comicvine.gamespot.com/absolute-batman...,3,"Alfred Pennyworth, Batman, Bibbo, Black Mask, ...","Bat-Suit, Batmobile, Utility Belt",Frank Martin Jr.,Nick Dragotta,Scott Snyder,"<p><em><b>NEW FRIENDS, NEW ENEMIES!</b></em></...",https://comicvine.gamespot.com/a/uploads/scale...,2024-12-18,160294.0
3,https://comicvine.gamespot.com/api/issue/4000-...,1089295,"The Zoo, Part Four",https://comicvine.gamespot.com/absolute-batman...,4,"Batman, Catwoman, Joe Chill, Randal Powers, Th...","Bat-Suit, Batmobile, Utility Belt",Frank Martin Jr.,Gabriel Hernandez Walta,"Nick Dragotta, Scott Snyder",<p><em>Absolute Batman has established himself...,https://comicvine.gamespot.com/a/uploads/scale...,2025-01-08,160294.0
4,https://comicvine.gamespot.com/api/issue/4000-...,1095530,"The Zoo, Part Five",https://comicvine.gamespot.com/absolute-batman...,5,"Alfred Pennyworth, Barbara Gordon, Batman, Bla...","Bat-Axe, Bat-Signal, Bat-Suit, Batarang, Batcy...",Frank Martin Jr.,Nick Dragotta,Scott Snyder,<p><em><b>WILL THE PARTY END HERE FOR ABSOLUTE...,https://comicvine.gamespot.com/a/uploads/scale...,2025-02-12,160294.0
5,https://comicvine.gamespot.com/api/issue/4000-...,1099460,"The Zoo, Part Six",https://comicvine.gamespot.com/absolute-batman...,6,"Alfred Pennyworth, Batman, Black Mask, Catwoma...","Bat-Axe, Bat-Signal, Bat-Suit, Batarang, Batcy...",Frank Martin Jr.,Nick Dragotta,Scott Snyder,<p><em>THIS IS IT!</em></p><p><em>CATCH UP TO ...,https://comicvine.gamespot.com/a/uploads/scale...,2025-03-19,160294.0
6,https://comicvine.gamespot.com/api/issue/4000-...,1102449,Absolute Zero,https://comicvine.gamespot.com/absolute-batman...,7,"Alfred Pennyworth, Batman, Killer Croc, Malone...",,Muntsa Vicente,Marcos Martín,Scott Snyder,<p><em><b>THE JOKER AND MR. FREEZE MAKE THEIR ...,https://comicvine.gamespot.com/a/uploads/scale...,2025-04-09,160294.0
7,https://comicvine.gamespot.com/api/issue/4000-...,1109522,Absolute Zero,https://comicvine.gamespot.com/absolute-batman...,8,"Batman, Joe Chill, Joker, Killer Croc, Malone,...",,Muntsa Vicente,Marcos Martín,Scott Snyder,<p><em><b>GOTHAM IN THE GRASP OF MR. FREEZE!</...,https://comicvine.gamespot.com/a/uploads/scale...,2025-05-14,160294.0
8,https://comicvine.gamespot.com/api/issue/4000-...,1115570,"Abomination, Part One",https://comicvine.gamespot.com/absolute-batman...,9,"Alfred Pennyworth, Bane, Barbara Gordon, Batma...",,Frank Martin Jr.,Nick Dragotta,Scott Snyder,<p><em><b>AN ALL NEW ARK (M) STARTS HERE!</b><...,https://comicvine.gamespot.com/a/uploads/scale...,2025-06-11,160294.0
9,https://comicvine.gamespot.com/api/issue/4000-...,1120416,"Abomination, Part Two",https://comicvine.gamespot.com/absolute-batman...,10,"Bane, Batman, Bibbo, Catwoman, James Gordon, K...",,Frank Martin,Nick Dragotta,Scott Snyder,<p><em><b>BRUCE WAYNE TRAPPED IN ARK M!</b></e...,https://comicvine.gamespot.com/a/uploads/scale...,2025-07-16,160294.0
10,https://comicvine.gamespot.com/api/issue/4000-...,1126983,"Abomination, Part Three",https://comicvine.gamespot.com/absolute-batman...,11,"Alfred Pennyworth, Bane, Batman, Joker, Pengui...",Venom,Ivan Plascencia,Clay Mann,Scott Snyder,<p><em>Learn the origin of Bane!</em></p><p><e...,https://comicvine.gamespot.com/a/uploads/scale...,2025-08-20,160294.0
11,https://comicvine.gamespot.com/api/issue/4000-...,1131749,"Abomination, Part Four",https://comicvine.gamespot.com/absolute-batman...,12,"Alfred Pennyworth, Bane, Batman, Carmine Falco...","Bat-Suit, Venom",Frank Martin,Nick Dragotta,Scott Snyder,<p><em><b>BANE PRESSES THE ATTACK!</b></em></p...,https://comicvine.gamespot.com/a/uploads/scale...,2025-09-10,160294.0
12,https://comicvine.gamespot.com/api/issue/4000-...,1137116,"Abomination, Part Five",https://comicvine.gamespot.com/absolute-batman...,13,"Alfred Pennyworth, Bane, Batman, Catwoman, Har...",,Frank Martin,Nick Dragotta,Scott Snyder,<p><em>ABSOLUTE CATWOMAN DEBUTS!</em></p><p><e...,https://comicvine.gamespot.com/a/uploads/scale...,2025-10-08,160294.0
13,https://comicvine.gamespot.com/api/issue/4000-...,1145497,"Abomination, Conclusion",https://comicvine.gamespot.com/absolute-batman...,14,"Alfred Pennyworth, Bane, Barbara Gordon, Batma...",,Frank Martin,Nick Dragotta,Scott Snyder,<p><em>BATMAN AND CATWOMAN VS. BANE!</em></p><...,https://comicvine.gamespot.com/a/uploads/scale...,2025-11-26,160294.0
14,https://comicvine.gamespot.com/api/issue/4000-...,1147554,The Joker,https://comicvine.gamespot.com/absolute-batman...,15,"Alfred Pennyworth, Batman, Joker",,Frank Martin,Jock,Scott Snyder,<p><em><b>SCOTT SNYDER REUNITES WITH LEGENDARY...,https://comicvine.gamespot.com/a/uploads/scale...,2025-12-10,160294.0
15,https://comicvine.gamespot.com/api/issue/4000-...,1154054,Bat Out of Hell,https://comicvine.gamespot.com/absolute-batman...,16,"Alfred Pennyworth, Batman, Killer Croc, Lucius...",Wonder Woman's Tiara,Frank Martin,Nick Dragotta,"Nick Dragotta, Scott Snyder",<p><em><b>ABSOLUTE BATMAN IN HELL!</b></em></p...,https://comicvine.gamespot.com/a/uploads/scale...,2026-01-28,160294.0
16,https://comicvine.gamespot.com/api/issue/4000-...,1156258,The Seventh Kingdom - Part 1,https://comicvine.gamespot.com/absolute-batman...,17,"Alfred Pennyworth, Barbara Gordon, Batman, Dic...",,Frank Martin Jr.,Eric Canete,Scott Snyder,<p><em>Dr. Pamela Isley has been unleashed fro...,https://comicvine.gamespot.com/a/uploads/scale...,2026-02-18,160294.0
17,https://comicvine.gamespot.com/api/issue/4000-...,1158997,The Seventh Kingdom - Part 2,https://comicvine.gamespot.com/absolute-batman...,18,"Alfred Pennyworth, Barbara Gordon, Batman, Dic...",,Frank Martin Jr.,Eric Canete,Scott Snyder,<p><em><b>ABSOLUTE IVY'S TENDRILS CONTINUE TO ...,https://comicvine.gamespot.com/a/uploads/scale...,2026-03-11,160294.0
18,https://comicvine.gamespot.com/api/issue/4000-...,1163009,The Straw Man,https://comicvine.gamespot.com/absolute-batman...,19,"Alfred Pennyworth, Barbara Gordon, Batman, Car...",Batmobile,Frank Martin Jr.,Nick Dragotta,Scott Snyder,<p><em>ABSOLUTE SCARECROW EMERGES FROM THE SHA...,https://comicvine.gamespot.com/a/uploads/scale...,2026-04-15,160294.0
19,https://comicvine.gamespot.com/api/issue/4000-...,1166236,The Straw Man,https://comicvine.gamespot.com/absolute-batman...,20,"Alfred Pennyworth, Batman, Dick Grayson, Duke ...",,Frank Martin Jr.,Nick Dragotta,Scott Snyder,<p><em><b>A TRAGIC LOSS ROCKS GOTHAM CITY!</b>...,https://comicvine.gamespot.com/a/uploads/scale...,2026-05-13,160294.0
20,https://comicvine.gamespot.com/api/issue/4000-...,1074563,"The Last Amazon, Part 1 of 5",https://comicvine.gamespot.com/absolute-wonder...,1,"Allan Fox, Apollo, Circe, Harbinger Prime, Peg...",Nemesis Lasso,Jordie Bellaire,Hayden Sherman,Kelly Thompson,<p><em><b>EISNER WINNER KELLY THOMPSON AND BRE...,https://comicvine.gamespot.com/a/uploads/scale...,2024-10-23,160511.0
21,https://comicvine.gamespot.com/api/issue/4000-...,1079209,"The Last Amazon, Part 2 of 5",https://comicvine.gamespot.com/absolute-wonder...,2,"Allan Fox, Circe, Commander Cole, Harbinger Pr...",Nemesis Lasso,Jordie Bellaire,Hayden Sherman,Kelly Thompson,<p><em><b>THOMPSON &amp; SHERMAN'S RED-HOT REI...,https://comicvine.gamespot.com/a/uploads/scale...,2024-11-27,160511.0
22,https://comicvine.gamespot.com/api/issue/4000-...,1085923,"The Last Amazon, Part 3 of 5",https://comicvine.gamespot.com/absolute-wonder...,3,"Allan Fox, Cheetah (Minerva), Circe, Commander...",Nemesis Lasso,Jordie Bellaire,Hayden Sherman,Kelly Thompson,<p><em><b>ENTER: STEVE TREVOR!</b></em></p><p>...,https://comicvine.gamespot.com/a/uploads/scale...,2024-12-26,160511.0
23,https://comicvine.gamespot.com/api/issue/4000-...,1090802,"The Last Amazon, Part 4 of 5",https://comicvine.gamespot.com/absolute-wonder...,4,"Allan Fox, Circe, Etta Candy, Gia Candy, Hecat...",Nemesis Lasso,Jordie Bellaire,Hayden Sherman,Kelly Thompson,<p><em><b>DIANA MAKES THE ULTIMATE SACRIFICE!<...,https://comicvine.gamespot.com/a/uploads/scale...,2025-01-22,160511.0
24,https://comicvine.gamespot.com/api/issue/4000-...,1096891,"The Last Amazon, Part 5 of 5",https://comicvine.gamespot.com/absolute-wonder...,5,"Cheetah (Minerva), Circe, Etta Candy, Gia Cand...","Wonder Woman's Bracelets, Wonder Woman's Tiara",Jordie Bellaire,Hayden Sherman,Kelly Thompson,<p><em><b>A COSMIC THREAT ENCROACHES ON GATEWA...,https://comicvine.gamespot.com/a/uploads/scale...,2025-02-26,160511.0
25,https://comicvine.gamespot.com/api/issue/4000-...,1100111,"The Lady or the Tiger, Part 1; Li'l Diana",https://comicvine.gamespot.com/absolute-wonder...,6,"Circe, Hades, Pegasus, Prometheus, Wonder Woman","Nemesis Lasso, Wonder Woman's Bracelets, Wonde...","Dustin Nguyen, Mattia de Iulis","Dustin Nguyen, Mattia de Iulis",Kelly Thompson,<p><em><b>THE SHOCKING ORIGIN OF DIANA'S DEADL...,https://comicvine.gamespot.com/a/uploads/scale...,2025-03-26,160511.0
26,https://comicvine.gamespot.com/api/issue/4000-...,1106021,"The Lady or the Tiger, Part 2; Li'l Diana",https://comicvine.gamespot.com/absolute-wonder...,7,"Chimera, Circe, Hades, Hecate, Pegasus, Persep...",,"Dustin Nguyen, Mattia de Iulis","Dustin Nguyen, Mattia de Iulis",Kelly Thompson,"<p><em><b>DIANA, LOST IN THE UNDERWORLD!</b></...",https://comicvine.gamespot.com/a/uploads/scale...,2025-04-23,160511.0
27,https://comicvine.gamespot.com/api/issue/4000-...,1112938,"As My Mothers Made Me, Part 1",https://comicvine.gamespot.com/absolute-wonder...,8,"Cheetah (Minerva), Doctor Poison, Etta Candy, ...",,Jordie Bellaire,Hayden Sherman,Kelly Thompson,"<p><em><b>""AS MY MOTHERS MADE ME,"" PART ONE!</...",https://comicvine.gamespot.com/a/uploads/scale...,2025-05-28,160511.0
28,https://comicvine.gamespot.com/api/issue/4000-...,1116606,"As My Mothers Made Me, Part 2 of 5",https://comicvine.gamespot.com/absolute-wonder...,9,"Cheetah (Minerva), Circe, Doctor Poison, Etta ...",,Jordie Bellaire,Hayden Sherman,Kelly Thompson,<p><em><b>CAN DIANA ESCAPE THE MAZE?!</b></em>...,https://comicvine.gamespot.com/a/uploads/scale...,2025-06-25,160511.0
29,https://comicvine.gamespot.com/api/issue/4000-...,1121439,As My Mothers Made Me. Part 3 of 5,https://comicvine.gamespot.com/absolute-wonder...,10,"Artemis, Cheetah (Minerva), Circe, Etta Candy,...",,Jordie Bellaire,Hayden Sherman,Kelly Thompson,<p><em><b>DIANA'S PATH GROWS EVEN MORE ELUSIVE...,https://comicvine.gamespot.com/a/uploads/scale...,2025-07-23,160511.0
30,https://comicvine.gamespot.com/api/issue/4000-...,1128888,"As My Mothers Made Me, Part 4 of 5",https://comicvine.gamespot.com/absolute-wonder...,11,"Artemis, Cheetah (Minerva), Etta Candy, Ferdin...","Nemesis Lasso, Wonder Woman's Bracelets, Wonde...",Jordie Bellaire,Hayden Sherman,Kelly Thompson,<p><em>HEAVY IS THE HEAD THAT WEARS THE CROWN!...,https://comicvine.gamespot.com/a/uploads/scale...,2025-08-27,160511.0
31,https://comicvine.gamespot.com/api/issue/4000-...,1134428,"As My Mothers Made Me, Part 5 of 5",https://comicvine.gamespot.com/absolute-wonder...,12,"Ara , Cheetah (Minerva), Cheetah (Rich), Cuca,...",,Jordie Bellaire,Hayden Sherman,Kelly Thompson,<p><em><b>AN ESCAPE FROM THE MAZE?!</b></em></...,https://comicvine.gamespot.com/a/uploads/scale...,2025-09-24,160511.0
32,https://comicvine.gamespot.com/api/issue/4000-...,1139062,"The Price, Part 1 of 2",https://comicvine.gamespot.com/absolute-wonder...,13,"Cheetah (Minerva), Etta Candy, Gia Candy, Stev...",,Jordie Bellaire,Matias Bergara,Kelly Thompson,<p><em><b>THE TRUTH OF THE AMAZONS!</b></em></...,https://comicvine.gamespot.com/a/uploads/scale...,2025-10-22,160511.0
33,https://comicvine.gamespot.com/api/issue/4000-...,1145498,"The Price, Part 2 of 2",https://comicvine.gamespot.com/absolute-wonder...,14,"Cheetah (Minerva), Etta Candy, Gaea, Gia Candy...","Peacemaker Helmet, Wonder Woman's Bracelets",Jordie Bellaire,Matias Bergara,Kelly Thompson,<p><em>WONDER WOMAN BATTLES…THE EARTH ITSELF?<...,https://comicvine.gamespot.com/a/uploads/scale...,2025-11-26,160511.0
34,https://comicvine.gamespot.com/api/issue/4000-...,1149795,The Mark of Hecate,https://comicvine.gamespot.com/absolute-wonder...,15,"Batman, Joker, Veronica Cale, Wonder Woman","Bat-Suit, Wonder Woman's Bracelets",Jordie Bellaire,Hayden Sherman,Kelly Thompson,<p><b>BECAUSE YOU DEMANDED IT: THE FIRST MEETI...,https://comicvine.gamespot.com/a/uploads/scale...,2025-12-24,160511.0
35,https://comicvine.gamespot.com/api/issue/4000-...,1154057,"Season of the Witch, Part 1 of 5",https://comicvine.gamespot.com/absolute-wonder...,16,"Aphrodite, Ara , Artemis, Cheetah (Minerva), C...",Wonder Woman's Tiara,Jordie Bellaire,Hayden Sherman,Kelly Thompson,<p><em><b>A NEW STORY ARC BEGINS AS DIANA CONF...,https://comicvine.gamespot.com/a/uploads/scale...,2026-01-28,160511.0
36,https://comicvine.gamespot.com/api/issue/4000-...,1156913,"Season of the Witch, Part 2 of 5",https://comicvine.gamespot.com/absolute-wonder...,17,"Ara , Cheetah (Minerva), Cheetah (Rich), Docto...",,Jordie Bellaire,Hayden Sherman,Kelly Thompson,"<p><em>WONDER WOMAN, BETRAYED!</em></p><p><em>...",https://comicvine.gamespot.com/a/uploads/scale...,2026-02-25,160511.0
37,https://comicvine.gamespot.com/api/issue/4000-...,1160262,"Season of the Witch, Part 3 of 5",https://comicvine.gamespot.com/absolute-wonder...,18,"Aphrodite, Ara , Cheetah (Minerva), Ferdinand,...",Wonder Woman's Tiara,Jordie Bellaire,Hayden Sherman,Kelly Thompson,<p><em>DIANA VS. ZATANNA!</em></p><p><em>What ...,https://comicvine.gamespot.com/a/uploads/scale...,2026-03-25,160511.0
38,https://comicvine.gamespot.com/api/issue/4000-...,1163573,"Season of the Witch, Part 4 of 5",https://comicvine.gamespot.com/absolute-wonder...,19,"Aphrodite, Cheetah (Minerva), Circe, Cuca, Ett...",Wonder Woman's Tiara,Jordie Bellaire,Hayden Sherman,Kelly Thompson,<p><em><b>ABSOLUTE WONDER WOMAN WILL NEVER BE ...,https://comicvine.gamespot.com/a/uploads/scale...,2026-04-22,160511.0
39,https://comicvine.gamespot.com/api/issue/4000-...,1168224,"Season of the Witch, Part 5 of 5",https://comicvine.gamespot.com/absolute-wonder...,20,"Cheetah (Minerva), Cheetah (Rich), Doctor Pois...",,Jordie Bellaire,Hayden Sherman,Kelly Thompson,"<p><em>""SEASON OF THE WITCH"" REACHES ITS BLOOD...",https://comicvine.gamespot.com/a/uploads/scale...,2026-05-27,160511.0

In [13]:
all_issues_df.to_csv("issues.csv")

### Develop

In [3]:
batman_volume=volumes['api_detail_url'][0]
batman_volume

'https://comicvine.gamespot.com/api/volume/4050-160294/'

In [15]:
API_KEY = os.getenv("API_KEY")
BASE_URL = "https://comicvine.gamespot.com/api/"
endpoint = "volumes/"
url = batman_volume

headers = {
    "User-Agent": "absolutePipeline"  
}

params = {
        "api_key": API_KEY,
        "format": "json", 
        "field_list": "issues"
}

batman_response = requests.get(url=url, params=params, headers=headers)

batman_response.json()

{'error': 'OK',
 'limit': 1,
 'offset': 0,
 'number_of_page_results': 1,
 'number_of_total_results': 1,
 'status_code': 1,
 'results': {'issues': [{'api_detail_url': 'https://comicvine.gamespot.com/api/issue/4000-1073108/',
    'id': 1073108,
    'name': 'The Zoo, Part One',
    'site_detail_url': 'https://comicvine.gamespot.com/absolute-batman-1-the-zoo-part-one/4000-1073108/',
    'issue_number': '1'},
   {'api_detail_url': 'https://comicvine.gamespot.com/api/issue/4000-1077465/',
    'id': 1077465,
    'name': 'The Zoo, Part Two',
    'site_detail_url': 'https://comicvine.gamespot.com/absolute-batman-2-the-zoo-part-two/4000-1077465/',
    'issue_number': '2'},
   {'api_detail_url': 'https://comicvine.gamespot.com/api/issue/4000-1083601/',
    'id': 1083601,
    'name': 'The Zoo, Part Three',
    'site_detail_url': 'https://comicvine.gamespot.com/absolute-batman-3-the-zoo-part-three/4000-1083601/',
    'issue_number': '3'},
   {'api_detail_url': 'https://comicvine.gamespot.com/api/issue/4000-1089295/',
    'id': 1089295,
    'name': 'The Zoo, Part Four',
    'site_detail_url': 'https://comicvine.gamespot.com/absolute-batman-4-the-zoo-part-four/4000-1089295/',
    'issue_number': '4'},
   {'api_detail_url': 'https://comicvine.gamespot.com/api/issue/4000-1095530/',
    'id': 1095530,
    'name': 'The Zoo, Part Five',
    'site_detail_url': 'https://comicvine.gamespot.com/absolute-batman-5-the-zoo-part-five/4000-1095530/',
    'issue_number': '5'},
   {'api_detail_url': 'https://comicvine.gamespot.com/api/issue/4000-1099460/',
    'id': 1099460,
    'name': 'The Zoo, Part Six',
    'site_detail_url': 'https://comicvine.gamespot.com/absolute-batman-6-the-zoo-part-six/4000-1099460/',
    'issue_number': '6'},
   {'api_detail_url': 'https://comicvine.gamespot.com/api/issue/4000-1102449/',
    'id': 1102449,
    'name': 'Absolute Zero',
    'site_detail_url': 'https://comicvine.gamespot.com/absolute-batman-7-absolute-zero/4000-1102449/',
    'issue_number': '7'},
   {'api_detail_url': 'https://comicvine.gamespot.com/api/issue/4000-1109522/',
    'id': 1109522,
    'name': 'Absolute Zero',
    'site_detail_url': 'https://comicvine.gamespot.com/absolute-batman-8-absolute-zero/4000-1109522/',
    'issue_number': '8'},
   {'api_detail_url': 'https://comicvine.gamespot.com/api/issue/4000-1115570/',
    'id': 1115570,
    'name': 'Abomination, Part One',
    'site_detail_url': 'https://comicvine.gamespot.com/absolute-batman-9-abomination-part-one/4000-1115570/',
    'issue_number': '9'},
   {'api_detail_url': 'https://comicvine.gamespot.com/api/issue/4000-1120416/',
    'id': 1120416,
    'name': 'Abomination, Part Two',
    'site_detail_url': 'https://comicvine.gamespot.com/absolute-batman-10-abomination-part-two/4000-1120416/',
    'issue_number': '10'},
   {'api_detail_url': 'https://comicvine.gamespot.com/api/issue/4000-1126983/',
    'id': 1126983,
    'name': 'Abomination, Part Three',
    'site_detail_url': 'https://comicvine.gamespot.com/absolute-batman-11-abomination-part-three/4000-1126983/',
    'issue_number': '11'},
   {'api_detail_url': 'https://comicvine.gamespot.com/api/issue/4000-1131749/',
    'id': 1131749,
    'name': 'Abomination, Part Four',
    'site_detail_url': 'https://comicvine.gamespot.com/absolute-batman-12-abomination-part-four/4000-1131749/',
    'issue_number': '12'},
   {'api_detail_url': 'https://comicvine.gamespot.com/api/issue/4000-1137116/',
    'id': 1137116,
    'name': 'Abomination, Part Five',
    'site_detail_url': 'https://comicvine.gamespot.com/absolute-batman-13-abomination-part-five/4000-1137116/',
    'issue_number': '13'},
   {'api_detail_url': 'https://comicvine.gamespot.com/api/issue/4000-1145497/',
    'id': 1145497,
    'name': 'Abomination, Conclusion',
    'site_detail_url': 'https://comicvine.gamespot.com/absolute-batman-14-abomination-conclusion/4000-1145497/',
    'issue_number': '14'},
   {'api_detail_url': 'https://comicvine.gamespot.com/api/issue/4000-1147554/',
    'id': 1147554,
    'name': 'The Joker',
    'site_detail_url': 'https://comicvine.gamespot.com/absolute-batman-15-the-joker/4000-1147554/',
    'issue_number': '15'},
   {'api_detail_url': 'https://comicvine.gamespot.com/api/issue/4000-1154054/',
    'id': 1154054,
    'name': 'Bat Out of Hell',
    'site_detail_url': 'https://comicvine.gamespot.com/absolute-batman-16-bat-out-of-hell/4000-1154054/',
    'issue_number': '16'},
   {'api_detail_url': 'https://comicvine.gamespot.com/api/issue/4000-1156258/',
    'id': 1156258,
    'name': 'The Seventh Kingdom - Part 1',
    'site_detail_url': 'https://comicvine.gamespot.com/absolute-batman-17-the-seventh-kingdom-part-1/4000-1156258/',
    'issue_number': '17'},
   {'api_detail_url': 'https://comicvine.gamespot.com/api/issue/4000-1158997/',
    'id': 1158997,
    'name': 'The Seventh Kingdom - Part 2',
    'site_detail_url': 'https://comicvine.gamespot.com/absolute-batman-18-the-seventh-kingdom-part-2/4000-1158997/',
    'issue_number': '18'},
   {'api_detail_url': 'https://comicvine.gamespot.com/api/issue/4000-1163009/',
    'id': 1163009,
    'name': 'The Straw Man',
    'site_detail_url': 'https://comicvine.gamespot.com/absolute-batman-19-the-straw-man/4000-1163009/',
    'issue_number': '19'},
   {'api_detail_url': 'https://comicvine.gamespot.com/api/issue/4000-1166236/',
    'id': 1166236,
    'name': 'The Straw Man',
    'site_detail_url': 'https://comicvine.gamespot.com/absolute-batman-20-the-straw-man/4000-1166236/',
    'issue_number': '20'}]},
 'version': '1.0'}

In [49]:
data = response.json()

with open("output.json", "w") as f:
    json.dump(data, f, indent=2)

In [50]:
issues = data["results"]["issues"]
df = pd.DataFrame(issues)
df

,api_detail_url,id,name,site_detail_url,issue_number
0,https://comicvine.gamespot.com/api/issue/4000-...,1073108,"The Zoo, Part One",https://comicvine.gamespot.com/absolute-batman...,1
1,https://comicvine.gamespot.com/api/issue/4000-...,1077465,"The Zoo, Part Two",https://comicvine.gamespot.com/absolute-batman...,2
2,https://comicvine.gamespot.com/api/issue/4000-...,1083601,"The Zoo, Part Three",https://comicvine.gamespot.com/absolute-batman...,3
3,https://comicvine.gamespot.com/api/issue/4000-...,1089295,"The Zoo, Part Four",https://comicvine.gamespot.com/absolute-batman...,4
4,https://comicvine.gamespot.com/api/issue/4000-...,1095530,"The Zoo, Part Five",https://comicvine.gamespot.com/absolute-batman...,5
5,https://comicvine.gamespot.com/api/issue/4000-...,1099460,"The Zoo, Part Six",https://comicvine.gamespot.com/absolute-batman...,6
6,https://comicvine.gamespot.com/api/issue/4000-...,1102449,Absolute Zero,https://comicvine.gamespot.com/absolute-batman...,7
7,https://comicvine.gamespot.com/api/issue/4000-...,1109522,Absolute Zero,https://comicvine.gamespot.com/absolute-batman...,8
8,https://comicvine.gamespot.com/api/issue/4000-...,1115570,"Abomination, Part One",https://comicvine.gamespot.com/absolute-batman...,9
9,https://comicvine.gamespot.com/api/issue/4000-...,1120416,"Abomination, Part Two",https://comicvine.gamespot.com/absolute-batman...,10
10,https://comicvine.gamespot.com/api/issue/4000-...,1126983,"Abomination, Part Three",https://comicvine.gamespot.com/absolute-batman...,11
11,https://comicvine.gamespot.com/api/issue/4000-...,1131749,"Abomination, Part Four",https://comicvine.gamespot.com/absolute-batman...,12
12,https://comicvine.gamespot.com/api/issue/4000-...,1137116,"Abomination, Part Five",https://comicvine.gamespot.com/absolute-batman...,13
13,https://comicvine.gamespot.com/api/issue/4000-...,1145497,"Abomination, Conclusion",https://comicvine.gamespot.com/absolute-batman...,14
14,https://comicvine.gamespot.com/api/issue/4000-...,1147554,The Joker,https://comicvine.gamespot.com/absolute-batman...,15
15,https://comicvine.gamespot.com/api/issue/4000-...,1154054,Bat Out of Hell,https://comicvine.gamespot.com/absolute-batman...,16
16,https://comicvine.gamespot.com/api/issue/4000-...,1156258,The Seventh Kingdom - Part 1,https://comicvine.gamespot.com/absolute-batman...,17
17,https://comicvine.gamespot.com/api/issue/4000-...,1158997,The Seventh Kingdom - Part 2,https://comicvine.gamespot.com/absolute-batman...,18
18,https://comicvine.gamespot.com/api/issue/4000-...,1163009,The Straw Man,https://comicvine.gamespot.com/absolute-batman...,19
19,https://comicvine.gamespot.com/api/issue/4000-...,1166236,The Straw Man,https://comicvine.gamespot.com/absolute-batman...,20

In [52]:

url = df['api_detail_url'][18]

headers = {
    "User-Agent": "absolutePipeline"  
}

params = {
        "api_key": API_KEY,
        "format": "json", 
        "field_list": ["date_last_updated,character_credits,description,id,image,object_credits,person_credits,store_date,volume"]
}

response = requests.get(url=url, params=params, headers=headers)

response.json()

{'error': 'OK',
 'limit': 1,
 'offset': 0,
 'number_of_page_results': 1,
 'number_of_total_results': 1,
 'status_code': 1,
 'results': {'character_credits': [{'api_detail_url': 'https://comicvine.gamespot.com/api/character/4005-5556/',
    'id': 5556,
    'name': 'Alfred Pennyworth',
    'site_detail_url': 'https://comicvine.gamespot.com/alfred-pennyworth/4005-5556/'},
   {'api_detail_url': 'https://comicvine.gamespot.com/api/character/4005-5368/',
    'id': 5368,
    'name': 'Barbara Gordon',
    'site_detail_url': 'https://comicvine.gamespot.com/barbara-gordon/4005-5368/'},
   {'api_detail_url': 'https://comicvine.gamespot.com/api/character/4005-1699/',
    'id': 1699,
    'name': 'Batman',
    'site_detail_url': 'https://comicvine.gamespot.com/batman/4005-1699/'},
   {'api_detail_url': 'https://comicvine.gamespot.com/api/character/4005-42288/',
    'id': 42288,
    'name': 'Carmine Falcone',
    'site_detail_url': 'https://comicvine.gamespot.com/carmine-falcone/4005-42288/'},
   {'api_detail_url': 'https://comicvine.gamespot.com/api/character/4005-3588/',
    'id': 3588,
    'name': 'Deathstroke',
    'site_detail_url': 'https://comicvine.gamespot.com/deathstroke/4005-3588/'},
   {'api_detail_url': 'https://comicvine.gamespot.com/api/character/4005-1691/',
    'id': 1691,
    'name': 'Dick Grayson',
    'site_detail_url': 'https://comicvine.gamespot.com/dick-grayson/4005-1691/'},
   {'api_detail_url': 'https://comicvine.gamespot.com/api/character/4005-100777/',
    'id': 100777,
    'name': 'Duke Thomas',
    'site_detail_url': 'https://comicvine.gamespot.com/duke-thomas/4005-100777/'},
   {'api_detail_url': 'https://comicvine.gamespot.com/api/character/4005-1696/',
    'id': 1696,
    'name': 'Harley Quinn',
    'site_detail_url': 'https://comicvine.gamespot.com/harley-quinn/4005-1696/'},
   {'api_detail_url': 'https://comicvine.gamespot.com/api/character/4005-3727/',
    'id': 3727,
    'name': 'James Gordon',
    'site_detail_url': 'https://comicvine.gamespot.com/james-gordon/4005-3727/'},
   {'api_detail_url': 'https://comicvine.gamespot.com/api/character/4005-6849/',
    'id': 6849,
    'name': 'Jason Todd',
    'site_detail_url': 'https://comicvine.gamespot.com/jason-todd/4005-6849/'},
   {'api_detail_url': 'https://comicvine.gamespot.com/api/character/4005-1702/',
    'id': 1702,
    'name': 'Joker',
    'site_detail_url': 'https://comicvine.gamespot.com/joker/4005-1702/'},
   {'api_detail_url': 'https://comicvine.gamespot.com/api/character/4005-3725/',
    'id': 3725,
    'name': 'Killer Croc',
    'site_detail_url': 'https://comicvine.gamespot.com/killer-croc/4005-3725/'},
   {'api_detail_url': 'https://comicvine.gamespot.com/api/character/4005-4885/',
    'id': 4885,
    'name': 'Penguin',
    'site_detail_url': 'https://comicvine.gamespot.com/penguin/4005-4885/'},
   {'api_detail_url': 'https://comicvine.gamespot.com/api/character/4005-3726/',
    'id': 3726,
    'name': 'Scarecrow',
    'site_detail_url': 'https://comicvine.gamespot.com/scarecrow/4005-3726/'},
   {'api_detail_url': 'https://comicvine.gamespot.com/api/character/4005-6156/',
    'id': 6156,
    'name': 'Stephanie Brown',
    'site_detail_url': 'https://comicvine.gamespot.com/stephanie-brown/4005-6156/'},
   {'api_detail_url': 'https://comicvine.gamespot.com/api/character/4005-9290/',
    'id': 9290,
    'name': 'Tim Drake',
    'site_detail_url': 'https://comicvine.gamespot.com/tim-drake/4005-9290/'},
   {'api_detail_url': 'https://comicvine.gamespot.com/api/character/4005-5555/',
    'id': 5555,
    'name': 'Two-Face',
    'site_detail_url': 'https://comicvine.gamespot.com/two-face/4005-5555/'}],
  'date_last_updated': '2026-04-18 18:00:54',
  'description': "<p><em>ABSOLUTE SCARECROW EMERGES FROM THE SHADOWS OF ARK M AS A NEW STORY ARC BEGINS...</em></p><p><em>Poison Ivy proved to be just one of the many horrors within the bowels of the ARK M facility, and as Joker sets his sights on Absolute Batman, he decides to enlist the help of one of the center's most terrifying doctors, Dr. Jonathan Crane.</em></p><p><em>While Bruce Wayne tries to align himself with Barbara Gordon, there's more than one alliance formed in this issue.</em></p><p><em>New debuts, new villains, new arc starts here.</em></p>",
  'id': 1163009,
  'image': {'icon_url': 'https://comicvine.gamespot.com/a/uploads/square_avatar/11161/111615891/10041672-cover.jpg',
   'medium_url': 'https://comicvine.gamespot.com/a/uploads/scale_medium/11161/111615891/10041672-cover.jpg',
   'screen_url': 'https://comicvine.gamespot.com/a/uploads/screen_medium/11161/111615891/10041672-cover.jpg',
   'screen_large_url': 'https://comicvine.gamespot.com/a/uploads/screen_kubrick/11161/111615891/10041672-cover.jpg',
   'small_url': 'https://comicvine.gamespot.com/a/uploads/scale_small/11161/111615891/10041672-cover.jpg',
   'super_url': 'https://comicvine.gamespot.com/a/uploads/scale_large/11161/111615891/10041672-cover.jpg',
   'thumb_url': 'https://comicvine.gamespot.com/a/uploads/scale_avatar/11161/111615891/10041672-cover.jpg',
   'tiny_url': 'https://comicvine.gamespot.com/a/uploads/square_mini/11161/111615891/10041672-cover.jpg',
   'original_url': 'https://comicvine.gamespot.com/a/uploads/original/11161/111615891/10041672-cover.jpg',
   'image_tags': 'All Images'},
  'object_credits': [{'api_detail_url': 'https://comicvine.gamespot.com/api/object/4055-41463/',
    'id': 41463,
    'name': 'Batmobile',
    'site_detail_url': 'https://comicvine.gamespot.com/batmobile/4055-41463/'}],
  'person_credits': [{'api_detail_url': 'https://comicvine.gamespot.com/api/person/4040-5033/',
    'id': 5033,
    'name': 'Ariel Olivetti',
    'site_detail_url': 'https://comicvine.gamespot.com/ariel-olivetti/4040-5033/',
    'role': 'cover'},
   {'api_detail_url': 'https://comicvine.gamespot.com/api/person/4040-42775/',
    'id': 42775,
    'name': 'Ben Oliver',
    'site_detail_url': 'https://comicvine.gamespot.com/ben-oliver/4040-42775/',
    'role': 'cover'},
   {'api_detail_url': 'https://comicvine.gamespot.com/api/person/4040-56273/',
    'id': 56273,
    'name': 'Chris Conroy',
    'site_detail_url': 'https://comicvine.gamespot.com/chris-conroy/4040-56273/',
    'role': 'editor'},
   {'api_detail_url': 'https://comicvine.gamespot.com/api/person/4040-52357/',
    'id': 52357,
    'name': 'Frank Martin Jr.',
    'site_detail_url': 'https://comicvine.gamespot.com/frank-martin-jr/4040-52357/',
    'role': 'colorist, cover'},
   {'api_detail_url': 'https://comicvine.gamespot.com/api/person/4040-61095/',
    'id': 61095,
    'name': 'Katie Kubert',
    'site_detail_url': 'https://comicvine.gamespot.com/katie-kubert/4040-61095/',
    'role': 'editor'},
   {'api_detail_url': 'https://comicvine.gamespot.com/api/person/4040-2629/',
    'id': 2629,
    'name': 'Liam Sharp',
    'site_detail_url': 'https://comicvine.gamespot.com/liam-sharp/4040-2629/',
    'role': 'cover'},
   {'api_detail_url': 'https://comicvine.gamespot.com/api/person/4040-25538/',
    'id': 25538,
    'name': 'Marie Javins',
    'site_detail_url': 'https://comicvine.gamespot.com/marie-javins/4040-25538/',
    'role': 'other'},
   {'api_detail_url': 'https://comicvine.gamespot.com/api/person/4040-41789/',
    'id': 41789,
    'name': 'Nick Dragotta',
    'site_detail_url': 'https://comicvine.gamespot.com/nick-dragotta/4040-41789/',
    'role': 'artist, cover'},
   {'api_detail_url': 'https://comicvine.gamespot.com/api/person/4040-132895/',
    'id': 132895,
    'name': 'Sabrina Futch',
    'site_detail_url': 'https://comicvine.gamespot.com/sabrina-futch/4040-132895/',
    'role': 'editor'},
   {'api_detail_url': 'https://comicvine.gamespot.com/api/person/4040-58926/',
    'id': 58926,
    'name': 'Scott Snyder',
    'site_detail_url': 'https://comicvine.gamespot.com/scott-snyder/4040-58926/',
    'role': 'writer'},
   {'api_detail_url': 'https://comicvine.gamespot.com/api/person/4040-83732/',
    'id': 83732,
    'name': 'Tom Napolitano',
    'site_detail_url': 'https://comicvine.gamespot.com/tom-napolitano/4040-83732/',
    'role': 'letterer'}],
  'store_date': '2026-04-15',
  'volume': {'api_detail_url': 'https://comicvine.gamespot.com/api/volume/4050-160294/',
   'id': 160294,
   'name': 'Absolute Batman',
   'site_detail_url': 'https://comicvine.gamespot.com/absolute-batman/4050-160294/'}},
 'version': '1.0'}

In [53]:
data = response.json()

with open("issue_details.json", "w") as f:
    json.dump(data, f, indent=2)

In [ ]:
#Get characters in issue
characters_json = data["results"]["character_credits"]
characters_list = []
for character in characters_json: 
    characters_list.append(character.get("name"))
    #print(character)
# get description
description= data["results"]["description"]
# get image
image_url = data["results"]["image"]["medium_url"]
# get objects
objects_json = data["results"]["object_credits"]
objects_list = []
for object in objects_json: 
    objects_list.append(object.get("name"))
# get credits
persons_json = data["results"]["person_credits"] 
for person in persons_json: 
    colorists = [p["name"] for p in persons_json if "colorist" in p.get("role", "")]
    artists = [p["name"] for p in persons_json if "artist" in p.get("role", "")]
    writers = [p["name"] for p in persons_json if "writer" in p.get("role", "")]
#  get store date
store_date = data["results"]["store_date"] 
# volume id
volume_id = data["results"]["volume"]["id"]

['Alfred Pennyworth',
 'Barbara Gordon',
 'Batman',
 'Carmine Falcone',
 'Deathstroke',
 'Dick Grayson',
 'Duke Thomas',
 'Harley Quinn',
 'James Gordon',
 'Jason Todd',
 'Joker',
 'Killer Croc',
 'Penguin',
 'Scarecrow',
 'Stephanie Brown',
 'Tim Drake',
 'Two-Face']

In [41]:
df.at[18, "characters"] = characters_list
df.at[18, "description"] = description
df.at[18, "image_url"] = image_url
df.at[18, "objects"] = objects_list
df.at[18, "colorists"] = colorists
df.at[18, "artists"] = artists
df.at[18, "writers"] = writers
df.at[18, "store_date"] = store_date
df.at[18, "volume_id"] = int(volume_id)
df

,api_detail_url,id,name,site_detail_url,issue_number,characters,description,image_url,objects,colorists,artists,writers,store_date,volume_id
0,https://comicvine.gamespot.com/api/issue/4000-...,1073108,"The Zoo, Part One",https://comicvine.gamespot.com/absolute-batman...,1,nan,NaN,NaN,nan,nan,nan,nan,NaN,NaN
1,https://comicvine.gamespot.com/api/issue/4000-...,1077465,"The Zoo, Part Two",https://comicvine.gamespot.com/absolute-batman...,2,nan,NaN,NaN,nan,nan,nan,nan,NaN,NaN
2,https://comicvine.gamespot.com/api/issue/4000-...,1083601,"The Zoo, Part Three",https://comicvine.gamespot.com/absolute-batman...,3,nan,NaN,NaN,nan,nan,nan,nan,NaN,NaN
3,https://comicvine.gamespot.com/api/issue/4000-...,1089295,"The Zoo, Part Four",https://comicvine.gamespot.com/absolute-batman...,4,nan,NaN,NaN,nan,nan,nan,nan,NaN,NaN
4,https://comicvine.gamespot.com/api/issue/4000-...,1095530,"The Zoo, Part Five",https://comicvine.gamespot.com/absolute-batman...,5,nan,NaN,NaN,nan,nan,nan,nan,NaN,NaN
5,https://comicvine.gamespot.com/api/issue/4000-...,1099460,"The Zoo, Part Six",https://comicvine.gamespot.com/absolute-batman...,6,nan,NaN,NaN,nan,nan,nan,nan,NaN,NaN
6,https://comicvine.gamespot.com/api/issue/4000-...,1102449,Absolute Zero,https://comicvine.gamespot.com/absolute-batman...,7,nan,NaN,NaN,nan,nan,nan,nan,NaN,NaN
7,https://comicvine.gamespot.com/api/issue/4000-...,1109522,Absolute Zero,https://comicvine.gamespot.com/absolute-batman...,8,nan,NaN,NaN,nan,nan,nan,nan,NaN,NaN
8,https://comicvine.gamespot.com/api/issue/4000-...,1115570,"Abomination, Part One",https://comicvine.gamespot.com/absolute-batman...,9,nan,NaN,NaN,nan,nan,nan,nan,NaN,NaN
9,https://comicvine.gamespot.com/api/issue/4000-...,1120416,"Abomination, Part Two",https://comicvine.gamespot.com/absolute-batman...,10,nan,NaN,NaN,nan,nan,nan,nan,NaN,NaN
10,https://comicvine.gamespot.com/api/issue/4000-...,1126983,"Abomination, Part Three",https://comicvine.gamespot.com/absolute-batman...,11,nan,NaN,NaN,nan,nan,nan,nan,NaN,NaN
11,https://comicvine.gamespot.com/api/issue/4000-...,1131749,"Abomination, Part Four",https://comicvine.gamespot.com/absolute-batman...,12,nan,NaN,NaN,nan,nan,nan,nan,NaN,NaN
12,https://comicvine.gamespot.com/api/issue/4000-...,1137116,"Abomination, Part Five",https://comicvine.gamespot.com/absolute-batman...,13,nan,NaN,NaN,nan,nan,nan,nan,NaN,NaN
13,https://comicvine.gamespot.com/api/issue/4000-...,1145497,"Abomination, Conclusion",https://comicvine.gamespot.com/absolute-batman...,14,nan,NaN,NaN,nan,nan,nan,nan,NaN,NaN
14,https://comicvine.gamespot.com/api/issue/4000-...,1147554,The Joker,https://comicvine.gamespot.com/absolute-batman...,15,nan,NaN,NaN,nan,nan,nan,nan,NaN,NaN
15,https://comicvine.gamespot.com/api/issue/4000-...,1154054,Bat Out of Hell,https://comicvine.gamespot.com/absolute-batman...,16,nan,NaN,NaN,nan,nan,nan,nan,NaN,NaN
16,https://comicvine.gamespot.com/api/issue/4000-...,1156258,The Seventh Kingdom - Part 1,https://comicvine.gamespot.com/absolute-batman...,17,nan,NaN,NaN,nan,nan,nan,nan,NaN,NaN
17,https://comicvine.gamespot.com/api/issue/4000-...,1158997,The Seventh Kingdom - Part 2,https://comicvine.gamespot.com/absolute-batman...,18,nan,NaN,NaN,nan,nan,nan,nan,NaN,NaN
18,https://comicvine.gamespot.com/api/issue/4000-...,1163009,The Straw Man,https://comicvine.gamespot.com/absolute-batman...,19,"[Alfred Pennyworth, Barbara Gordon, Batman, Ca...",<p><em>ABSOLUTE SCARECROW EMERGES FROM THE SHA...,https://comicvine.gamespot.com/a/uploads/scale...,[Batmobile],[Frank Martin Jr.],[Nick Dragotta],[Scott Snyder],2026-04-15,160294.0
19,https://comicvine.gamespot.com/api/issue/4000-...,1166236,The Straw Man,https://comicvine.gamespot.com/absolute-batman...,20,nan,NaN,NaN,nan,nan,nan,nan,NaN,NaN

### Populate data of all issues

In [18]:
batman_issues_data = batman_response.json()
issues = batman_issues_data["results"]["issues"]
batman_issues_df = pd.DataFrame(issues)
batman_issues_df

,api_detail_url,id,name,site_detail_url,issue_number
0,https://comicvine.gamespot.com/api/issue/4000-...,1073108,"The Zoo, Part One",https://comicvine.gamespot.com/absolute-batman...,1
1,https://comicvine.gamespot.com/api/issue/4000-...,1077465,"The Zoo, Part Two",https://comicvine.gamespot.com/absolute-batman...,2
2,https://comicvine.gamespot.com/api/issue/4000-...,1083601,"The Zoo, Part Three",https://comicvine.gamespot.com/absolute-batman...,3
3,https://comicvine.gamespot.com/api/issue/4000-...,1089295,"The Zoo, Part Four",https://comicvine.gamespot.com/absolute-batman...,4
4,https://comicvine.gamespot.com/api/issue/4000-...,1095530,"The Zoo, Part Five",https://comicvine.gamespot.com/absolute-batman...,5
5,https://comicvine.gamespot.com/api/issue/4000-...,1099460,"The Zoo, Part Six",https://comicvine.gamespot.com/absolute-batman...,6
6,https://comicvine.gamespot.com/api/issue/4000-...,1102449,Absolute Zero,https://comicvine.gamespot.com/absolute-batman...,7
7,https://comicvine.gamespot.com/api/issue/4000-...,1109522,Absolute Zero,https://comicvine.gamespot.com/absolute-batman...,8
8,https://comicvine.gamespot.com/api/issue/4000-...,1115570,"Abomination, Part One",https://comicvine.gamespot.com/absolute-batman...,9
9,https://comicvine.gamespot.com/api/issue/4000-...,1120416,"Abomination, Part Two",https://comicvine.gamespot.com/absolute-batman...,10
10,https://comicvine.gamespot.com/api/issue/4000-...,1126983,"Abomination, Part Three",https://comicvine.gamespot.com/absolute-batman...,11
11,https://comicvine.gamespot.com/api/issue/4000-...,1131749,"Abomination, Part Four",https://comicvine.gamespot.com/absolute-batman...,12
12,https://comicvine.gamespot.com/api/issue/4000-...,1137116,"Abomination, Part Five",https://comicvine.gamespot.com/absolute-batman...,13
13,https://comicvine.gamespot.com/api/issue/4000-...,1145497,"Abomination, Conclusion",https://comicvine.gamespot.com/absolute-batman...,14
14,https://comicvine.gamespot.com/api/issue/4000-...,1147554,The Joker,https://comicvine.gamespot.com/absolute-batman...,15
15,https://comicvine.gamespot.com/api/issue/4000-...,1154054,Bat Out of Hell,https://comicvine.gamespot.com/absolute-batman...,16
16,https://comicvine.gamespot.com/api/issue/4000-...,1156258,The Seventh Kingdom - Part 1,https://comicvine.gamespot.com/absolute-batman...,17
17,https://comicvine.gamespot.com/api/issue/4000-...,1158997,The Seventh Kingdom - Part 2,https://comicvine.gamespot.com/absolute-batman...,18
18,https://comicvine.gamespot.com/api/issue/4000-...,1163009,The Straw Man,https://comicvine.gamespot.com/absolute-batman...,19
19,https://comicvine.gamespot.com/api/issue/4000-...,1166236,The Straw Man,https://comicvine.gamespot.com/absolute-batman...,20

In [ ]:
headers = {
    "User-Agent": "absolutePipeline"  
}

params = {
        "api_key": API_KEY,
        "format": "json", 
        "field_list": ["date_last_updated,character_credits,description,id,image,object_credits,person_credits,store_date,volume"]
}

for col in ["characters", "objects", "colorists", "artists", "writers"]:
    batman_issues_df[col] = None
for row in batman_issues_df.itertuples():
    print(f"{row.Index} calling {row.api_detail_url}")
    url = batman_issues_df['api_detail_url'][row.Index]

    response = requests.get(url=url, params=params, headers=headers)
    data = response.json()

    characters_json = data["results"]["character_credits"]
    characters_list = []
    for character in characters_json: 
        characters_list.append(character.get("name"))

    description= data["results"]["description"]

    image_url = data["results"]["image"]["medium_url"]

    objects_json = data["results"]["object_credits"]
    objects_list = []
    for object in objects_json: 
        objects_list.append(object.get("name"))
   
    persons_json = data["results"]["person_credits"] 
    for person in persons_json: 
        colorists = [p["name"] for p in persons_json if "colorist" in p.get("role", "")]
        artists = [p["name"] for p in persons_json if "artist" in p.get("role", "")]
        writers = [p["name"] for p in persons_json if "writer" in p.get("role", "")]
    
    store_date = data["results"]["store_date"] 
    volume_id = data["results"]["volume"]["id"]

    batman_issues_df.at[row.Index, "characters"] = characters_list
    batman_issues_df.at[row.Index, "description"] = description
    batman_issues_df.at[row.Index, "image_url"] = image_url
    batman_issues_df.at[row.Index, "objects"] = objects_list
    batman_issues_df.at[row.Index, "colorists"] = colorists
    batman_issues_df.at[row.Index, "artists"] = artists
    batman_issues_df.at[row.Index, "writers"] = writers
    batman_issues_df.at[row.Index, "store_date"] = store_date
    batman_issues_df.at[row.Index, "volume_id"] = int(volume_id)

    time.sleep(5)

for col in ["characters", "objects", "colorists", "artists", "writers"]:
    batman_issues_df[col] = batman_issues_df[col].apply(
        lambda x: ", ".join(x) if isinstance(x, list) else x
    )

0 calling https://comicvine.gamespot.com/api/issue/4000-1073108/
1 calling https://comicvine.gamespot.com/api/issue/4000-1077465/
2 calling https://comicvine.gamespot.com/api/issue/4000-1083601/
3 calling https://comicvine.gamespot.com/api/issue/4000-1089295/
4 calling https://comicvine.gamespot.com/api/issue/4000-1095530/
5 calling https://comicvine.gamespot.com/api/issue/4000-1099460/
6 calling https://comicvine.gamespot.com/api/issue/4000-1102449/
7 calling https://comicvine.gamespot.com/api/issue/4000-1109522/
8 calling https://comicvine.gamespot.com/api/issue/4000-1115570/
9 calling https://comicvine.gamespot.com/api/issue/4000-1120416/
10 calling https://comicvine.gamespot.com/api/issue/4000-1126983/
11 calling https://comicvine.gamespot.com/api/issue/4000-1131749/
12 calling https://comicvine.gamespot.com/api/issue/4000-1137116/
13 calling https://comicvine.gamespot.com/api/issue/4000-1145497/
14 calling https://comicvine.gamespot.com/api/issue/4000-1147554/
15 calling https://comicvine.gamespot.com/api/issue/4000-1154054/
16 calling https://comicvine.gamespot.com/api/issue/4000-1156258/
17 calling https://comicvine.gamespot.com/api/issue/4000-1158997/
18 calling https://comicvine.gamespot.com/api/issue/4000-1163009/
19 calling https://comicvine.gamespot.com/api/issue/4000-1166236/

In [ ]:

batman_issues_df

,api_detail_url,id,name,site_detail_url,issue_number,characters,objects,colorists,artists,writers,description,image_url,store_date,volume_id
0,https://comicvine.gamespot.com/api/issue/4000-...,1073108,"The Zoo, Part One",https://comicvine.gamespot.com/absolute-batman...,1,"Alfred Pennyworth, Barbara Gordon, Batman, Bla...","Bat-Suit, Batmobile, Utility Belt",Frank Martin Jr.,Nick Dragotta,Scott Snyder,<p><em><b>BATMAN LEGEND SCOTT SNYDER AND ICONI...,https://comicvine.gamespot.com/a/uploads/scale...,2024-10-09,160294.0
1,https://comicvine.gamespot.com/api/issue/4000-...,1077465,"The Zoo, Part Two",https://comicvine.gamespot.com/absolute-batman...,2,"Alfred Pennyworth, Barbara Gordon, Batman, Bla...","Bat-Suit, Batmobile",Frank Martin Jr.,Nick Dragotta,Scott Snyder,<p><em><b>SNYDER AND DRAGOTTA'S BRAND-NEW TAKE...,https://comicvine.gamespot.com/a/uploads/scale...,2024-11-13,160294.0
2,https://comicvine.gamespot.com/api/issue/4000-...,1083601,"The Zoo, Part Three",https://comicvine.gamespot.com/absolute-batman...,3,"Alfred Pennyworth, Batman, Bibbo, Black Mask, ...","Bat-Suit, Batmobile, Utility Belt",Frank Martin Jr.,Nick Dragotta,Scott Snyder,"<p><em><b>NEW FRIENDS, NEW ENEMIES!</b></em></...",https://comicvine.gamespot.com/a/uploads/scale...,2024-12-18,160294.0
3,https://comicvine.gamespot.com/api/issue/4000-...,1089295,"The Zoo, Part Four",https://comicvine.gamespot.com/absolute-batman...,4,"Batman, Catwoman, Joe Chill, Randal Powers, Th...","Bat-Suit, Batmobile, Utility Belt",Frank Martin Jr.,Gabriel Hernandez Walta,"Nick Dragotta, Scott Snyder",<p><em>Absolute Batman has established himself...,https://comicvine.gamespot.com/a/uploads/scale...,2025-01-08,160294.0
4,https://comicvine.gamespot.com/api/issue/4000-...,1095530,"The Zoo, Part Five",https://comicvine.gamespot.com/absolute-batman...,5,"Alfred Pennyworth, Barbara Gordon, Batman, Bla...","Bat-Axe, Bat-Signal, Bat-Suit, Batarang, Batcy...",Frank Martin Jr.,Nick Dragotta,Scott Snyder,<p><em><b>WILL THE PARTY END HERE FOR ABSOLUTE...,https://comicvine.gamespot.com/a/uploads/scale...,2025-02-12,160294.0
5,https://comicvine.gamespot.com/api/issue/4000-...,1099460,"The Zoo, Part Six",https://comicvine.gamespot.com/absolute-batman...,6,"Alfred Pennyworth, Batman, Black Mask, Catwoma...","Bat-Axe, Bat-Signal, Bat-Suit, Batarang, Batcy...",Frank Martin Jr.,Nick Dragotta,Scott Snyder,<p><em>THIS IS IT!</em></p><p><em>CATCH UP TO ...,https://comicvine.gamespot.com/a/uploads/scale...,2025-03-19,160294.0
6,https://comicvine.gamespot.com/api/issue/4000-...,1102449,Absolute Zero,https://comicvine.gamespot.com/absolute-batman...,7,"Alfred Pennyworth, Batman, Killer Croc, Malone...",,Muntsa Vicente,Marcos Martín,Scott Snyder,<p><em><b>THE JOKER AND MR. FREEZE MAKE THEIR ...,https://comicvine.gamespot.com/a/uploads/scale...,2025-04-09,160294.0
7,https://comicvine.gamespot.com/api/issue/4000-...,1109522,Absolute Zero,https://comicvine.gamespot.com/absolute-batman...,8,"Batman, Joe Chill, Joker, Killer Croc, Malone,...",,Muntsa Vicente,Marcos Martín,Scott Snyder,<p><em><b>GOTHAM IN THE GRASP OF MR. FREEZE!</...,https://comicvine.gamespot.com/a/uploads/scale...,2025-05-14,160294.0
8,https://comicvine.gamespot.com/api/issue/4000-...,1115570,"Abomination, Part One",https://comicvine.gamespot.com/absolute-batman...,9,"Alfred Pennyworth, Bane, Barbara Gordon, Batma...",,Frank Martin Jr.,Nick Dragotta,Scott Snyder,<p><em><b>AN ALL NEW ARK (M) STARTS HERE!</b><...,https://comicvine.gamespot.com/a/uploads/scale...,2025-06-11,160294.0
9,https://comicvine.gamespot.com/api/issue/4000-...,1120416,"Abomination, Part Two",https://comicvine.gamespot.com/absolute-batman...,10,"Bane, Batman, Bibbo, Catwoman, James Gordon, K...",,Frank Martin,Nick Dragotta,Scott Snyder,<p><em><b>BRUCE WAYNE TRAPPED IN ARK M!</b></e...,https://comicvine.gamespot.com/a/uploads/scale...,2025-07-16,160294.0
10,https://comicvine.gamespot.com/api/issue/4000-...,1126983,"Abomination, Part Three",https://comicvine.gamespot.com/absolute-batman...,11,"Alfred Pennyworth, Bane, Batman, Joker, Pengui...",Venom,Ivan Plascencia,Clay Mann,Scott Snyder,<p><em>Learn the origin of Bane!</em></p><p><e...,https://comicvine.gamespot.com/a/uploads/scale...,2025-08-20,160294.0
11,https://comicvine.gamespot.com/api/issue/4000-...,1131749,"Abomination, Part Four",https://comicvine.gamespot.com/absolute-batman...,12,"Alfred Pennyworth, Bane, Batman, Carmine Falco...","Bat-Suit, Venom",Frank Martin,Nick Dragotta,Scott Snyder,<p><em><b>BANE PRESSES THE ATTACK!</b></em></p...,https://comicvine.gamespot.com/a/uploads/scale...,2025-09-10,160294.0
12,https://comicvine.gamespot.com/api/issue/4000-...,1137116,"Abomination, Part Five",https://comicvine.gamespot.com/absolute-batman...,13,"Alfred Pennyworth, Bane, Batman, Catwoman, Har...",,Frank Martin,Nick Dragotta,Scott Snyder,<p><em>ABSOLUTE CATWOMAN DEBUTS!</em></p><p><e...,https://comicvine.gamespot.com/a/uploads/scale...,2025-10-08,160294.0
13,https://comicvine.gamespot.com/api/issue/4000-...,1145497,"Abomination, Conclusion",https://comicvine.gamespot.com/absolute-batman...,14,"Alfred Pennyworth, Bane, Barbara Gordon, Batma...",,Frank Martin,Nick Dragotta,Scott Snyder,<p><em>BATMAN AND CATWOMAN VS. BANE!</em></p><...,https://comicvine.gamespot.com/a/uploads/scale...,2025-11-26,160294.0
14,https://comicvine.gamespot.com/api/issue/4000-...,1147554,The Joker,https://comicvine.gamespot.com/absolute-batman...,15,"Alfred Pennyworth, Batman, Joker",,Frank Martin,Jock,Scott Snyder,<p><em><b>SCOTT SNYDER REUNITES WITH LEGENDARY...,https://comicvine.gamespot.com/a/uploads/scale...,2025-12-10,160294.0
15,https://comicvine.gamespot.com/api/issue/4000-...,1154054,Bat Out of Hell,https://comicvine.gamespot.com/absolute-batman...,16,"Alfred Pennyworth, Batman, Killer Croc, Lucius...",Wonder Woman's Tiara,Frank Martin,Nick Dragotta,"Nick Dragotta, Scott Snyder",<p><em><b>ABSOLUTE BATMAN IN HELL!</b></em></p...,https://comicvine.gamespot.com/a/uploads/scale...,2026-01-28,160294.0
16,https://comicvine.gamespot.com/api/issue/4000-...,1156258,The Seventh Kingdom - Part 1,https://comicvine.gamespot.com/absolute-batman...,17,"Alfred Pennyworth, Barbara Gordon, Batman, Dic...",,Frank Martin Jr.,Eric Canete,Scott Snyder,<p><em>Dr. Pamela Isley has been unleashed fro...,https://comicvine.gamespot.com/a/uploads/scale...,2026-02-18,160294.0
17,https://comicvine.gamespot.com/api/issue/4000-...,1158997,The Seventh Kingdom - Part 2,https://comicvine.gamespot.com/absolute-batman...,18,"Alfred Pennyworth, Barbara Gordon, Batman, Dic...",,Frank Martin Jr.,Eric Canete,Scott Snyder,<p><em><b>ABSOLUTE IVY'S TENDRILS CONTINUE TO ...,https://comicvine.gamespot.com/a/uploads/scale...,2026-03-11,160294.0
18,https://comicvine.gamespot.com/api/issue/4000-...,1163009,The Straw Man,https://comicvine.gamespot.com/absolute-batman...,19,"Alfred Pennyworth, Barbara Gordon, Batman, Car...",Batmobile,Frank Martin Jr.,Nick Dragotta,Scott Snyder,<p><em>ABSOLUTE SCARECROW EMERGES FROM THE SHA...,https://comicvine.gamespot.com/a/uploads/scale...,2026-04-15,160294.0
19,https://comicvine.gamespot.com/api/issue/4000-...,1166236,The Straw Man,https://comicvine.gamespot.com/absolute-batman...,20,"Alfred Pennyworth, Batman, Dick Grayson, Duke ...",,Frank Martin Jr.,Nick Dragotta,Scott Snyder,<p><em><b>A TRAGIC LOSS ROCKS GOTHAM CITY!</b>...,https://comicvine.gamespot.com/a/uploads/scale...,2026-05-13,160294.0

In [23]:
batman_issues_df.to_csv("batman_issues.csv")